### ISSUE TITLE
Macros are not available in Swift

### ISSUE THREAD

**Issue by danyalaytekin** [AliSoftware/OHHTTPStubs#100]
e.g. `OHPathForFileInBundle`

**Comment by AliSoftware** [comment]
Good point. But given that those macros use `self.class` to know the context they are called from, do you have a suggestion on how we could achieve a similar behavior in Swift?

**Comment by AliSoftware** [comment]
Hi, 

This has just been fixed on `master`.

Note: I still want to make some other (unrelated) modifications before pushing version `4.0.0` so there is no official tag/version yet, but there will be soon (probably tomorrow).

**Comment by danyalaytekin** [comment]
Great, that's the route I'd have recommended. :+1:
