### ISSUE TITLE
Update GitHub Releases page from Changelog for 4.0.0 and 4.0.1

### ISSUE THREAD

**Issue by cdzombak** [AliSoftware/OHHTTPStubs#101]
[The Releases page](https://github.com/AliSoftware/OHHTTPStubs/releases) hasn't been updated with the latest info from [the Changelog](https://github.com/AliSoftware/OHHTTPStubs/blob/master/CHANGELOG.md) for versions 4.0.0 and 4.0.1:

![screen shot 2015-05-13 at 14 35 42](https://cloud.githubusercontent.com/assets/102904/7618048/60089dba-f97d-11e4-87fb-e672bb54e9de.png)

This is obviously very low priority, and I know it's unfortunate busy work, but it would be somewhat helpful if you could update those releases when you have a moment.

Thanks!

**Comment by AliSoftware** [comment]
Good catch!
Done 😃 Thx :+1:

**Comment by cdzombak** [comment]
@AliSoftware thank _you_!
