### ISSUE TITLE
Carthage Archive

### ISSUE THREAD

**Issue by tibr** [AliSoftware/OHHTTPStubs#102]
It would be great if you could attach [prebuilt framework archives](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file) to the releases so that Carthage users don't have to build OHHTTPStubs locally which is especially useful to speed up CI builds.

This can be done pretty easily:
```
carthage build --no-skip-current
carthage archive OHHTTPStubs
```

**Comment by AliSoftware** [comment]
I just did it for 4.0.2 and attached the `OHHTTPStubs.framework.zip` to the 4.0.2 release.

@tibr Could you tell me if that works and if I did it correctly? (I'm not a Carthage user, more fan of CocoaPods, so I'm not sure how to ensure I did it properly)

**Comment by tibr** [comment]
Works great, thanks a lot :+1:
