### ISSUE TITLE
onStubActivation is called twice when responseTime is > 0

### ISSUE THREAD

**Issue by gabro** [AliSoftware/OHHTTPStubs#106]
If I don't set `responseTime` `onStubActivation`'s handler is called once per stubbed request, as expected.

Conversely, is `responseTime` is > 0, the handler is called once when the request starts and once when the response is returned.

I believe this is a bug.

**Comment by gabro** [comment]
As a temporary workaround, I'm doing something like this in order to log each stubbed request only once

```
[...]
static var loggedRequests = Set<NSURLRequest>()
[...]
OHHTTPStubs.onStubActivation { (request: NSURLRequest!, stub: OHHTTPStubsDescriptor!) in
  if !self.loggedRequests.contains(request) {
    self.loggedRequests.insert(request)
    [...]
  }
}

```

**Comment by AliSoftware** [comment]
Hi @gabro 

Sorry for the delay, I haven't forgotten about your issue, but I've been busy lately and didn't have time to look at it yet.

Hopefully will have some time soon to check that use case and try to fix it (if you have a sample project that demonstrate the issue, I'm interested ;-))

**Comment by AliSoftware** [comment]
Hi @gabro 

I can't reproduce the issue with my demo project.

For example using [the OHHTTPStubsDemo project you can find in that repo](https://github.com/AliSoftware/OHHTTPStubs/blob/master/Examples/Swift), where [`onStubActivation` is setup in the `viewDidLoad`](https://github.com/AliSoftware/OHHTTPStubs/blob/master/Examples/Swift/MainViewController.swift#L31-L33), even as [the stub is setup with a `responseTime != 0`](https://github.com/AliSoftware/OHHTTPStubs/blob/master/Examples/Swift/MainViewController.swift#L84), `onStubActivation` is only called once per request.

I'm guessing it has to do with how you setup you stubs in your own project.
Could you provide a sample project so I can reproduce the issue? I won't be able to do much without being able to reproducing it.

**Comment by AliSoftware** [comment]
Closing due to lack of response.
