### ISSUE TITLE
Testing a successful response with empty response data using OHTTPStubsResponse

### ISSUE THREAD

**Issue by manuyavuz** [AliSoftware/OHHTTPStubs#113]
Hi,

I want to stub a network request's response which contains empty response data when request succeeds. Server just sends a status code of 200 and does not return any response data. 

Currently I can't test this scenario because all `responseWith*` methods take a `nonnull` input parameter.
I think these input parameters should be able to get also nil as an input.

Is there any other way to handle this with the current version? If not, what do you think about my proposal?

**Comment by AliSoftware** [comment]
Simply return a `responseWithData:` with an empty (0-length) `[NSData data]`.

**Comment by manuyavuz** [comment]
Ok, it worked because setting it does not call `-connection:didReceiveData:` delegate method at all, which means we simply received an empty response.

Thanks for the quick response.
