### ISSUE TITLE
Swift subspec not loading via Podfile

### ISSUE THREAD

**Issue by dtrenz** [AliSoftware/OHHTTPStubs#122]
Podfile
```ruby
pod 'OHHTTPStubs'
pod 'OHHTTPStubs/Swift'
```

CLI Output:
```
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `OHHTTPStubs/Swift` required by `Podfile`
```

**Comment by AliSoftware** [comment]
If you want any pod containing Swift code (like the `OHHTTPStubs/Swift` subspec but it's the same for any other pod containing Swift) you have to activate `use_frameworks!` in your Podfile.

See the CocoaPods documentation, or [CocoaPods' Blog post about this](http://blog.cocoapods.org/CocoaPods-0.36/) or [this raywenderlich tutorial](http://www.raywenderlich.com/97014/use-cocoapods-with-swift)
