### ISSUE TITLE
Unable to stub HTTP requests in Xcode 7 Automated UI tests

### ISSUE THREAD

**Issue by dtrenz** [AliSoftware/OHHTTPStubs#124]
I'm trying to test out OHHTTPStubs for stubbing HTTP requests made during automated UI tests in Xcode 7.

No matter what I try, I can't get my stub to capture any requests.

Here's what my setUp method looks like in my UI test file:

```swift
override func setUp() {
    super.setUp()

    let matcher: OHHTTPStubsTestBlock = { (request) -> Bool in
      return true
    }
    
    OHHTTPStubs.stubRequestsPassingTest(matcher) { (response) -> OHHTTPStubsResponse! in
      return OHHTTPStubsResponse.init()
    }
}
```

When I drop a breakpoint on the `return true` line, it never gets hit.

I have a unit test target that stubs HTTP requests just fine.

Has anyone else tried to use OHHTTPStubs with Xcode 7 UI tests? I'm stumped.

**Comment by Munchery-KleinLieu** [comment]
Bump...I get this during unit tests too :/

**Comment by dtrenz** [comment]
As I continue to research the issue, it looks like this might not be possible. Unlike unit tests, it appears that UI test code executes in an completely separate module and therefore cannot directly access or modify the underlying app logic that is under test.

I think the only way you could use OHHTTPStubs in UI tests would be to build them into the actual app — disabled by default — and then enable the stubs via some launch argument sent in when running UI tests.

I'd love to hear other options.

**Comment by AliSoftware** [comment]
Hi all,

Xcode 7 UI Tests are executed by running the application bundle in the simulator then driving it using `XCUI…` commands. Thus the tests are [Hosted Tests, as described in my wiki page here](https://github.com/AliSoftware/OHHTTPStubs/wiki/A-tricky-case-with-Application-Tests) meaning that it's the app bundle that gets launched (then the UI tests bundle is injected into the app bundle).

So @dtrenz is right, given how UI tests work, the only way to stub your requests during UI testing is to install your `OHHTTPStubs` in your app bundle (which is the one being run), not in your test bundle.

As @dtrenz mentioned, I suggest you use `XCUIApplication`'s `launchArgument` property to inject some special argument when running your stubs for UI testing, so you can differentiate it from a normal run, and install your `OHHTTPStubs` for UI tests only. See also [this page](http://masilotti.com/ui-testing-xcode-7/) for great suggestions.

**Comment by dtrenz** [comment]
Excellent response. Thanks, Ali!

**Comment by collinsrj** [comment]
After a suggestion from Ali, I have successfully setup stubs in my main application. I took the approach suggested using the launch options for the XCUIApplication.
I wanted to have my test cases responsible for the definition of the stub. To make this happen I'm playing with passing stub definition in the XCUIApplication.launchEnvironment. E.g. in my test case define an environment variable named 'HTTP_STUB_SOME_TEST' with a value something like '{"host":"example.com","statusCode":200, "data": ... }'
In my application code, inside a debug block I look at NSProcessInfo().environment and check for variables with names starting with "HTTP_STUB_', parse the JSON definition and create the stubs the usual way.

**Comment by dtrenz** [comment]
Very nice. 

Did you create a class that manages this and call it in `applicationDidFinishLaunching`?

**Comment by collinsrj** [comment]
@dtrenz yes, that's exactly what I did. It's a bit of a  hack. I haven't tried it with any substantial amount of data. I'm not sure how much can be passed through the environment. At the moment I'm still experimenting. Certainly for my small mocks at the moment it's working fine.

**Comment by AliSoftware** [comment]
Simple idea: maybe instead of passing the JSON when it's too big, you could instead pass the name (or path) of the fixture (JSON file) to use instead, and then use the file content to create your stub

**Comment by dtrenz** [comment]
So, I tried this and got it working, but I'm backing off for now because I don't love having to include so much test code/fixtures in my primary app target. But I can attest that this does work. I would love to see how others find more elegant solutions to this.

**Comment by tcamin** [comment]
We just released our library [SBTUITestTunnel](https://github.com/Subito-it/SBTUITestTunnel) which kinda worksaround the issue. At the app's launch we instantiate a web server on the app that conveniently translates requests coming from UI Test code. The big advantage over launchArguments is that you can dynamically modify app's behavior during test execution
Currently you can stub HTTP (of course using OHHTTPStubs 😀), download/upload files to app's sandbox, monitor HTTP requests (a sort of proxy), access to NSUserDefaults. Give it a try, hope this helps!

**Comment by kumarSC** [comment]
Hey @collinsrj and @dtrenz , I have been trying to setup stubs for UI tests but couldn't get it work correctly, could you please share some code which demonstrates how we can use launchArguments and  Stub setup in main app bundle using applicationDidFinishLaunching().

**Comment by kleinlieu** [comment]
@kumarSC what's your setup look like? Make sure your `OHHTTPStubs` pod is built with the application target and not the testing target. That was key for me.

**Comment by kumarSC** [comment]
Hey @kleinlieu , thanks for the response.I followed the instructions here to setup `OHHTTPStubs `, https://github.com/AliSoftware/OHHTTPStubs/wiki/A-tricky-case-with-Application-Tests. I am using XCUIApplication.launchEnvironment to pass a JSON to app bundle to setup the stubs.Later in the main app bundle where we are using `OHHTTPStubs` for faking network data we are using `applicationDidFinishLaunching ` to setup app for unit test.

```
final class TestingAppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?
    func applicationDidFinishLaunching(application: UIApplication) {
        NetworkConnectionChecker.start()
        window = UIWindow()
        window?.rootViewController = UIViewController()
        window?.makeKeyAndVisible()
```
In order to setup the stubs for UI tests, I need to figure out how I can initialize all the stubs and call them in `applicationDidFinishLaunching` for use in UI tests.
