### ISSUE TITLE
Fix the umbrella header

### ISSUE THREAD

**Issue by AliSoftware** [AliSoftware/OHHTTPStubs#127]
It seems to be broken (see #121)

Probably because:

1. The file named `OHHTTPStubs.h`, which should be my umbrella header, is also the header for one of the classes in the framework (actually the main one, but not the only one), so that's not really a header dedicated for umbrella imports
2. When splitting the library into subspecs, that could be optionally opt-in, I have to conditionally import the other headers in that umbrella header, and this logic might not work in all environments / integration contexts

Maybe one possible solution would be to start by having a dedicated umbrella header, even if it's not called `OHHTTPStubs.h` but rather `OHHTTPStubs-Umbrella.h` for example (I think we can override the default umbrella header in the build settings).

**Comment by jshier** [comment]
This may be related to what I'm seeing in Xcode 7.1. In OHHTTPStubs.h, line 32, I get an error: `Include of non-modular header inside framework module OHHTTPStubs.OHHTTPStubs`. This is using CocoaPods as such: 
```ruby
  pod 'OHHTTPStubs/Core'
  pod 'OHHTTPStubs/NSURLSession'
  pod 'OHHTTPStubs/JSON'
  pod 'OHHTTPStubs/OHPathHelpers'
  pod 'OHHTTPStubs/Swift'
```

**Comment by keith** [comment]
We're seeing this error as well.

**Comment by billyto** [comment]
I tried settting "Allow Non-modular includes in Framework Modules" in Build Settings to YES, but no luck, anyone has another workaround?

**Comment by keith** [comment]
I was able to fix this by manually changing the imports in `OHHTTPStubs.h` with:

```
#import "Compatibility.h"
#import "OHHTTPStubsResponse.h"
```

**Comment by AliSoftware** [comment]
@billyto 
> I tried setting "Allow Non-modular includes in Framework Modules" to YES

Yeah, even if that worked, that would be a workaround to cheat the compiler, wouldn't solve the core issue

@keith Ah interesting. I was wondering if it would be necessary to create a custom umbrella header and a custom modulemap to use it, but if this fix of yours is enough I'd say let's do that instead!

**Comment by keith** [comment]
I'm not sure how that affects users not pulling this in via CocoaPods though.

**Comment by AliSoftware** [comment]
I'm currently downloading Xcode 7.1 (I have seen this issue with Xcode 7, but it was not deterministic and sometimes worked, sometimes failed, so hopefully Xcode 7.1 will make it fail every time so I can be sure to know whether the patch fix it or not.

Will then indeed need to try a lot of contexts / configurations then, especially how it affects people not using CocoaPods, or using some subspecs but not all, etc. Will have to double-check with that trick using `#if __has_include` which I'm not sure is working properly in _every_ environment (CocoaPods vs. Carthage vs. Rome etc)

Will keep you posted, but interested if you guys could then test this in multiple different configurations afterwards.

**Comment by AliSoftware** [comment]
@keith did you only do these changes and nothing else?

```diff
-#import <OHHTTPStubs/Compatibility.h>
-#import <OHHTTPStubs/OHHTTPStubsResponse.h>
+#import "Compatibility.h"
+#import "OHHTTPStubsResponse.h"
```

Because if I'm doing that, and then try to build the framework directly from Xcode in the `OHHTTPStubs.xcworkspace`, I then get the "Include of non-modular header inside framework module" error on lines 188/191/194/197 :unamused:

**Comment by keith** [comment]
Yep that's all I changed.

**Comment by AliSoftware** [comment]
Mmmmh strange it doesn't work here then.

Could you try with the fix I started in `fix/umbrella-header` branch? (Like make your `Podfile` point to that branch and tell if it fixes it)? Thx!

**Comment by keith** [comment]
Yep, it built fine for me!

**Comment by AliSoftware** [comment]
Ok made some more fixes in #131, @keith @billyto @jshier could you test by making your Podfiles point to that branch and confirm it works for y'all? If so, I'll merge and release a new version!

**Comment by billyto** [comment]
Pointing at 
```
:branch => 'fix/umbrella-header'
```
It worked in my tests!
<img width="140" alt="screen shot 2015-10-22 at 8 53 30 pm" src="https://cloud.githubusercontent.com/assets/137653/10682086/165d39f8-78ff-11e5-9b85-ff790ae64fb0.png">

**Comment by jshier** [comment]
Fixed my build as well.

**Comment by AliSoftware** [comment]
Cool! Will do a release probably in the week-end (too busy today). Thx for the feedback :tada:

**Comment by incanus** [comment]
The fix branch is working great in my testing on several projects, too.

**Comment by AliSoftware** [comment]
Version `4.4.0` is out fixing all this. Thanks to you all for the feedback!

**Comment by madoke** [comment]
Can still reproduce this issue on XCode 7.2 / CocoaPods 0.39.0 when doing a fresh `pod install` (after removing the Pods folder) with the following Podfile configuration:

`target 'AppCoreTests' do
    use_frameworks!
    
    pod 'OHHTTPStubs'
    pod 'OHHTTPStubs/Swift'
end`

I can workaround it, however by commenting out the line `pod 'OHHTTPStubs/Swift'`, doing a `pod install`, then uncommenting it and doing a `pod install` again.

**Comment by AliSoftware** [comment]
@madoke That's a known bug of CP 0.39 i believe.

**Comment by AliSoftware** [comment]
Yeah just confirmed. Should be fixed in latest betas of CP though, so I encourage you to test the latest CocoaPods 1.0.0 beta.
