### ISSUE TITLE
Switching stubs while testing a polling network operation introduces race condition.

### ISSUE THREAD

**Issue by alexkent** [AliSoftware/OHHTTPStubs#133]
I am writing unit tests for a polling network call. e.g. we repeatedly call a URL until we get the response we want.

In my unit tests I first setup a OHHTTPStub with the unwanted data (http status 404 for example), begin the poller, then have a `dispatch_after` call (on main queue) which replaces the OHHTTPStub after a period of time with the wanted data. When replacing, I first call +removeStub on the existing stub, then add the replacement.

This is all works great… except it appears to introduce a race condition.
Sometimes, not every time, the NSURLSession.dataTaskWithRequest call returns with the following error:

`Error Domain=OHHTTPStubs Code=500 "It seems like the stub has been removed BEFORE the response had time to be sent."`

Is there a way around this? Is this a known limitation?

**Comment by AliSoftware** [comment]
The race condition is not really in OHHTTPStubs, but with your code removing and adding stubs while there are requests (using them) still running (sent and not having replied yet).
You mustn't remove stubs while the corresponding request is still pending.

Instead, to implement such a behavior, you should modify the stub response that you return in your stub depending on some condition. For example (in Swift):

```swift
var send404 = true
stub( isHost("mywebservice.com") && isPath("/foo/bar") ) { request in
  if send404 { // First time, return a 404
    return fixture(fixturePathInBundleFor404, status: 404)
    send404 = false
  } else { // Next time, return a 200
    return fixture(fixturePathInBundleFor200)
  }
}
```

**Comment by alexkent** [comment]
Thanks a lot for your help!
(and this great library!)
