### ISSUE TITLE
Can OHHTTPStubs stub GCDAsyncSocket requests?

### ISSUE THREAD

**Issue by mikelupo** [AliSoftware/OHHTTPStubs#138]
Thanks!

**Comment by AliSoftware** [comment]
Nope
As described in the README, `OHHTTPStubs` uses Cocoa URL Loading System to intercept all network calls made via NSURLRequests and the like.
I believe GCDAsyncSocket uses low-level, C API sockets so we have no way to intercept those low-level networking sockets with NSURLProtocol.
