### ISSUE TITLE
Unable to access whether stubs are currently enabled or not

### ISSUE THREAD

**Issue by engineeringman** [AliSoftware/OHHTTPStubs#139]
I'd like to add a runtime window that will enable us to toggle the enabled state of OHHTTPStubs at runtime.  However there's no way to know whether OHHTTPStubs is currently enabled or not, so I have no idea of which state to set my toggle switch on startup without making assumptions.  This seems like a property that should exist.

**Comment by AliSoftware** [comment]
Sorry not to have responded earlier, I got tons of stuff to do and forgot this.

That could definitely be a property to add. Won't have much time to add it soon though, but don't hesitate to make a PR to add it, that shouldn't be too complicated to implement :wink:

**Comment by jzucker2** [comment]
I saw this and decided to take a run at the idea. Let me know what you think https://github.com/AliSoftware/OHHTTPStubs/pull/159

**Comment by jzucker2** [comment]
Just in case you forgot, you can close this now :)

**Comment by AliSoftware** [comment]
Good poin, thanks!
