### ISSUE TITLE
  "_OHPathForFile", referenced from: undefined symbols

### ISSUE THREAD

**Issue by Voley** [AliSoftware/OHHTTPStubs#142]
I'm using OHHTTPStubs for my API testing and it works fine. But when I try to read json from file, it fails on linking. I use cocoapods with OHHTTPStubs included in main target, but not test target.

Here is how I include it in test:
`#import <OHHTTPStubs.h>`
`#import <OHPathHelpers.h>`

Here is the code:

    [OHHTTPStubs stubRequestsPassingTest:^BOOL(NSURLRequest * _Nonnull request) {        
        return [request.URL.absoluteString containsString:reportsForHouseEndpoint];
    } withStubResponse:^OHHTTPStubsResponse * _Nonnull(NSURLRequest * _Nonnull request) {
        NSString* fixture = OHPathForFile(@"reports.json", self.class);
        return [OHHTTPStubsResponse responseWithFileAtPath:fixture
                                                statusCode:200 headers:@{@"Content-Type":@"application/json"}];
    }];

Here is the error:

Undefined symbols for architecture x86_64:
  "_OHPathForFile", referenced from:
      ___31-[ApiReportsForHouseTest setUp]_block_invoke_2 in ApiReportsForHouseTest.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by samirGuerdah** [comment]
Hello,

You have this linking error because you are referencing the OHHTTPStubs library in your test class "ApiReportsForHouseTest". Remove any reference to the OHHTTPStubs or add the dependency to the test target. (Be sure that all the source files imported in the ApiReportsForHouseTest class don't reference(import) any class from OHHTTPStubs library.)

**Comment by AliSoftware** [comment]
Yep, what Samir said.

You can also see my wiki page explaining how Xcode do unit tests and especially how the test bundle is dynamically loaded into the host target (usually the app) at runtime by Xcode, explaining what you got there. Not related to OHHTTPStubs per se but to how Xcode handle things and how target linking works, so doing what Samir said should fix your configuration.

**Comment by Voley** [comment]
If I remove headers, I get 'Use of undeclared identifier: OHHTTPStubs'

**Comment by AliSoftware** [comment]
Of course you would. That's how headers work :smiley:
Why would you just remove headers instead of following Samir's instructions and fix your Podfile?

**Comment by Voley** [comment]
Ok i will try and report back

**Comment by AliSoftware** [comment]
Any news? Can we close this?
