### ISSUE TITLE
Support for PATCH HTTP method?

### ISSUE THREAD

**Issue by attheodo** [AliSoftware/OHHTTPStubs#145]
Any chance we can have a little nifty method `isMethodPATCH()` for HTTP Patch requests?

**Comment by AliSoftware** [comment]
Good idea indeed!

Could you maybe make a Pull Request? (with the new method + some tests on the same model as the other for isGET etc + crediting yourself in the CHANGELOG)

Thx!

**Comment by attheodo** [comment]
Sure, no problem. Thanks

Kind regards, 
AT.
