### ISSUE TITLE
OHHTTPStubsSwift not available in tests

### ISSUE THREAD

**Issue by ogezue** [AliSoftware/OHHTTPStubs#147]
I try to use OHHTTPStubs in a swift project to test my Alamofire-Requests but the methods defined in OHHTTPStubsSwift are not found.

Here my podfile:
````
platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

pod 'Alamofire', '~> 3.1.4'
pod 'AlamofireObjectMapper', '~> 2.1.0'
pod 'RealmSwift', '~> 0.97.0'
pod 'KeychainAccess', '~> 2.3.3'
pod 'Mattress', '~> 1.0.2'
pod 'ReachabilitySwift', '~> 2.3.3'
pod 'SwiftyBeaver', '~> 0.3.1'

target 'MyAppTests' do
   pod 'OHHTTPStubs'
   pod 'OHHTTPStubs/Swift'
end
```

And here a test I'm currently creating:

```
import XCTest
import OHHTTPStubs
import RealmSwift
@testable import ZEventApp

class OverviewModelTests: XCTestCase {

    var stub: OHHTTPStubsDescriptor?
    
    override func setUp() {
        super.setUp()
    
        
        stub(isHost("mywebservice.com")) { _ in
            let stubPath = OHPathForFile("Overview.json", self.dynamicType)
            isMethodGet
            
            return fixture(stubPath!, headers: ["Content-Type":"application/json"])
        }
        
    }
    //http(.GET, uri: URLs.sharedInstance.overviewItemsUrl())


    func testFetchOverviewItems() {
        
        let overviewModel = OverviewModel()
        
        overviewModel.fetchOverviewItemList({ (itemList: List<OverviewItem>) -> () in
            
            XCTAssertTrue(itemList.count == 6)
            })
            { (error: ErrorType?) -> () in
                XCTFail("Error in testFetchOverviewItems ")
            }
    }
}
```
Can you see, why the methods are not resolved? And would it be possible to add a test example in the example project?

**Comment by AliSoftware** [comment]
Where are your actual errors?

Does Xcode only complain on not knowing the methods `stub()` and/or `isHost`?
Or does it also complain in not being able to `import OHHTTPStubs`?
Or does it only complain in not finding `OHPathForFile`?

**Comment by ogezue** [comment]
Wow - fastes response time ever in github ever! :+1: 

It can resolve 
-import OHHTTPStubs
-stub(isHost("mywebservice.com"))

But not
-fixture(stubPath!, headers: ["Content-Type":"application/json"])
- or isMethodGet("")

The swift files is existing in the pod directory in my project.

**Comment by AliSoftware** [comment]
`isMethodGet` does not exist. The actual function name is `isMethodGET`

As for `fixture(…)` what is the actual error? Maybe it's not that it can't find the function, but just because the parameters don't match what it expects so it can't find a function… with the matching parameter types?

**Comment by ogezue** [comment]
Yes, I meant isMethodGET sorry for writing it wrong here. But XCode even can not find it if I type it correctly. 
The error is:
OverviewModelTests.swift:26:20: Cannot convert return expression of type 'OHHTTPStubsResponse' to return type 'Response'

But the core of the problem is that it ignores the methods in your swift-wrapper.

**Comment by AliSoftware** [comment]
It doesn't ignore `stub` or `isHost` so I don't think that's because the source of the Swift wrapper is not seen, but rather a type error in the code (with Xcode maybe printing a misleading error message?).

The Xcode error you reported is quite revealing actually. I wonder if Xcode converted the ObjC type `OHHTTPStubsResponse` into Swift as `OHHTTPStubs.Response`, namespacing the class automagically. What Xcode version are you using?

**Comment by ogezue** [comment]
I'm using XCode 7.2.
I changed the method to this:

```
    override func setUp() {
        super.setUp()
    
        stub(isMethodGET("mywebservice.com/get")) { _ in
            let stubPath = OHPathForFile("Overview.json", self.dynamicType)
            
            return fixture(stubPath!, headers: ["Content-Type":"application/json"])
        }
        
        /*
        stub(isHost("mywebservice.com")) { _ in
            let stubPath = OHPathForFile("Overview.json", self.dynamicType)
            //isMethodGet("")
            
           return fixture(stubPath!, headers: ["Content-Type":"application/json"])
        }
        */   
    }
```

and now I'm getting
 Cannot call value of non-function type 'OHHTTPStubsDescriptor?'

**Comment by AliSoftware** [comment]
On what?

**Comment by AliSoftware** [comment]
And isMethodGET expects a request not a string, what are you doing with
your code ?!
Le mar. 12 janv. 2016 à 12:55, Olivier Halligon <olivier@halligon.net> a
écrit :

> On what?

**Comment by ogezue** [comment]
Ok - forget this example. I copied a slightly modified piece of your example project into my test with the same error.
To be sure I added the modified code to your project where it compiles fine.

```
var mytextStub = stub(isExtension("txt")) { _ in
            let stubPath = OHPathForFile("stub.txt", self.dynamicType)
            return fixture(stubPath!, headers: ["Content-Type":"text/plain"])
        }
```

Error : Cannot convert return expression of type 'OHHTTPStubsResponse' to return type 'Response' in line 
```
return fixture(stubPath!, headers: ["Content-Type":"text/plain"])
```

**Comment by AliSoftware** [comment]
Ok could you create a sample/minimalist project and post it there so I can
take a closer look?

**Comment by ogezue** [comment]
Because my example project worked fine - I cleared my cocoapods cache and reloaded all pods again. Now this is working...

**Comment by hammadzz** [comment]
I am having the same issue. Super confused by what could possibly be causing this issue.

```
let obj: [String:Any] = [:]
let code: Int32 = 200
let headers = ["Content-Type": "application/json; charset=utf-8"]
stub(isPath("api/trade/create")) { _ in
      return OHHTTPStubsResponse(jsonObject: obj, statusCode: code, headers: headers)
 }
```

**Comment by seifscape** [comment]
I am actually running into the same error, with Xcode 9.0.1 and Swift 4 Project
