### ISSUE TITLE
Problem stubing specific url

### ISSUE THREAD

**Issue by ogezue** [AliSoftware/OHHTTPStubs#148]
I try to stub a specific url with this code:

```
        self.httpStubHeader = stub(isPath("http://www.myserver.com/ressources/objects")) { _ in
            let stubPath = OHPathForFile("objetcs.json", self.dynamicType)
            
            return fixture(stubPath!,status: 200 ,headers:
                ["Content-Type":"application/json"])
        }
```

but the stub is never called. isPath is evaluated successfully. What am I doing wrong? Perhaps this could be added to the usage examples?

**Comment by AliSoftware** [comment]
The `isPath` function checks for the URL **path**, as the name implies. Not the the whole URL.

**Comment by ogezue** [comment]
But this doesn't work either?

```
self.httpStubHeader = stub(isPath("/ressources/objects")) { _ in
            let stubPath = OHPathForFile("objetcs.json", self.dynamicType)

            return fixture(stubPath!,status: 200 ,headers:
                ["Content-Type":"application/json"])
 ```

**Comment by AliSoftware** [comment]
So instead you should:

1) either pass your own matcher (closure testing the request), which is probably the most direct and simple approach in your case:

```swift
stub( { request in request.URL.absoluteString == "http://www.myserver.com/ressources/objects" } ) { _ in
  …
}
```

You could of course separate this testing code in a dedicated function if you find it more readable:
```swift
// Reminder: the OHHTTPStubsTestBlock is a type alias for (NSURLRequest->Bool)
func testURL(urlString: String) -> OHHTTPStubsTestBlock {
  return { request in request.URL.absoluteString == urlString }
}
stub( testURL("http://www.myserver.com/ressources/objects") ) { _ in
  …
}
```

2) Or you could instead create a matcher by combining the various matchers that are provided by `OHHTTPStubs/Swift`

```swift
stub(isHost("www.myserver.com") && isPath("/resources/objects")) {
  ...
}
```

**Comment by AliSoftware** [comment]
> But this doesn't work either?

Probably because the path of the URL you're trying to stub is not **exactly** that one.
For example I noticed that you made a typo in your URL path, as the correct spelling for the word is `resources` not `ressources`, so maybe that's it…

If you're not sure why it differs you can still put a breakpoint in `isPath` and check what values are being compared to see why they mismatch and thus where your typo is. Or you can provide your own `OHHTTPStubsTestBlock` instead of using the convenience function `isPath` and use it to log stuff here until you manage to debug what's mistyped or wrong in your code.

**Comment by ogezue** [comment]
Thank you! This here was exactly what I was looking for and should be mentioned in the examples:

```
stub( { request in request.URL.absoluteString == "http://www.myserver.com/ressources/objects" } ) { _ in
  …
}
```

**Comment by johndpope-karhoo** [comment]
this sample code switching may help https://github.com/paulononaka/swift_restfull_sample/blob/a67e77f120583b3c76ad3da374c3672bf88e9e68/vivira_health_ios/Stubs/HTTPStub.swift
