### ISSUE TITLE
Reading header info

### ISSUE THREAD

**Issue by vicmosin** [AliSoftware/OHHTTPStubs#151]
Is there any way to read header information that was provided by request? Something like:
```
stub(isHost(host)) { request in
   if (request.getHeader("Accept-Language") == "en-US") {
      return one;
   } else {
      return other;
   }
}
```

**Comment by AliSoftware** [comment]
Use `NSURLRequest`'s `allHTTPHeaderFields` property. [See here in the documentation](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSURLRequest_Class/#//apple_ref/occ/instp/NSURLRequest/allHTTPHeaderFields).
