### ISSUE TITLE
Unable to use Swift code on OSX 10.9+

### ISSUE THREAD

**Issue by JeanAzzopardi** [AliSoftware/OHHTTPStubs#155]
I am wondering if there are any objections to bumping up the minimum deployment target of OSX to 10.9 (i.e. Mavericks) and allowing the swift code to be run on OSX too?

I've submitted #154 - would be grateful for any feedback please.

**Comment by AliSoftware** [comment]
Sure, sorry I haven't got back to you earlier I've been busy.
I'm gonna review #154 and merge it as soon as I've tested everything :wink:

**Comment by JeanAzzopardi** [comment]
Thanks!
