### ISSUE TITLE
Link Error on OHPathForFile

### ISSUE THREAD

**Issue by jkunzelman** [AliSoftware/OHHTTPStubs#158]
I am using this with the Cedar BDD test framework. When trying to use OHPathForFile I get the following during linking:

Undefined symbols for architecture x86_64:
  "OHPathForFile(NSString*, objc_class*)", referenced from:
      ___49-[GILocationUpdateOperationSpec declareBehaviors]_block_invoke_4 in GILocationUpdateOperationSpec.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by AliSoftware** [comment]
How did you integrate my library? CocoaPods ?
What subspec did you integrate in your Podfile?

**Comment by AliSoftware** [comment]
Especially, the `OHPathHelper` subspec is only included by default if you ask only for `pod 'OHHTTPStubs'` (or the `pod 'OHHTTPStubs/Default'` subspec, which is the same as this is the default subspec)

So if you only included `pod 'OHHTTPStubs/Swift'` then this subspec only brings the Swift wrapper (and the`Core` subspec it depends on) but not `NSURLSession` support, `JSON` helpers nor `OHPathHelper` which explains why it would not have been linked.

So typically you should specify both `pod 'OHHTTPStubs/Swift` and  `pod 'OHHTTPStubs'` (or `pod 'OHHTTPStubs/Default'`) if you want both the Swift wrapper and the commonly used helpers.

**Comment by jkunzelman** [comment]
I'm importing with Cocoapods.

I tried 
pod 'OHHTTPStubs/Default' 

which didn't seem to make a difference over just
pod 'OHHTTPStubs'

I was able to just load my service data in as an by loading into an NSDATA object first with a regular file load.

Since then I've ran into another problem. I'm using AFNetworking and doing my requests thru a AFURLSessionManager. My web service calls are then done with the dataTaskWithRequest:completionHandler method. 

I can see that my requests are hitting the stub using onStubActivation and naming my stub with the .name property.

However the completionHandler block never executes.  The session manager looks right and my code executes outside of tests correctly.

Thanks for you quick response on the first issue!

**Comment by AliSoftware** [comment]
Well of course using `pod 'OHHTTPStubs/Default'` instead of `pod 'OHHTTPStubs'` didn't change anything, as explained in my first answer they are the same :wink:

You must include both the root spec and the Swift addition:

```ruby
pod 'OHHTTPStubs' # This will get you the Default subspec including Core, NSURLSession support, JSON helper and OHPathHelpers
pod 'OHHTTPStubs/Swift' # This will add the Swift API
```
Only doing one of those two will only get just what you ask not both.

**Comment by AliSoftware** [comment]
For your second issue just check the condition you put in your stubs are correct. e.g maybe you added a stub for `foo/bar` but the request being sent by AFNetworking is in fact `foo/bar/` for example with a training slash or something.

**Comment by jkunzelman** [comment]
I looked like I was having issues with where the Stub was set up. I saw some commentary on the web about making sure you set up the stubs at the right time in the url session lifecycle before any requests are issued. that seem to fix my issue.

**Comment by AliSoftware** [comment]
Yep, someone opened #126 because they were having a similar issue (creating the NSURLSession too early, whereas the `OHHTTPStubs` framework patches the `NSURLSessionConfiguration` to catch the requests, so it needs to be loaded before any `NSURLSession` is created otherwise `NSURLSession` created before `OHHTTPStubs` had time to load won't be patched)

Did you fix all your issues, can we close this?

**Comment by jkunzelman** [comment]
closing. Thanks for you help!
