### ISSUE TITLE
Add `isMethodPATCH` to Swift utilities

### ISSUE THREAD

**Issue by krodak** [AliSoftware/OHHTTPStubs#164]
```Swift
public func isMethodPATCH() -> OHHTTPStubsTestBlock {
    return { $0.HTTPMethod == "PATCH" }
}
```

There are actually some APIs using this one :-)

**Comment by AliSoftware** [comment]
This method already exists since version 4.7.0.

**Comment by krodak** [comment]
My bad, CP is fetching me 4.6.0...

**Comment by AliSoftware** [comment]
Probably because either you're asking it to, by constraining your version in your `Podfile`, or because it's constrained by your `Podfile.lock` and you're only doing a `pod install` rather than a `pod update OHHTTPStubs`…

**Comment by krodak** [comment]
Unfortunately, only defining explicit Pod location fixed issue for me:
```
  pod 'OHHTTPStubs', :git => 'https://github.com/AliSoftware/OHHTTPStubs'
  pod 'OHHTTPStubs/Swift', :git => 'https://github.com/AliSoftware/OHHTTPStubs'
```

But this is CP issue, so sorry to bother with whole issue.

**Comment by AliSoftware** [comment]
I don't see any CP issue here, this kind of configuration has always worked for me even in CP 1.0.0 betas . You probably forgot to use `pod update` or have another pod in your Podfile which has a stricter dependency (your Podfile.lock) will tell you which)
