### ISSUE TITLE
Mocktail headers not parsed correctly?

### ISSUE THREAD

**Issue by Ashton-W** [AliSoftware/OHHTTPStubs#170]
Firstly, thanks so much for OHHTTPStubs.

I'm running into this error with loading stubs from Mocktail files:
`Request failed: unacceptable content-type: content-type: application/json`

From reading the code and this [test project](https://github.com/JinlianWang/TestHTTPStubs/blob/master/TestHTTPStubs/logos_ebay.tail#L4) it looks like Line 4 of Mocktail files is always interpreted as the value of the `Content-Type` header.

The documentation and reference implementation here https://github.com/puls/objc-mocktail/blob/master/Mocktail/Mocktail.m#L247 (which was transferred from the `square` github account to `puls`) shows that Line 4 and every following line until a blank line are interpreted header keys and values.

Fixing this might be considered an breaking change. But since the Mocktail format is far from standardized we could accept both formats by checking for a colon `:` on Line 4.

---
PS: Is HTTPMessage similar to Mocktail? I tried to find some documentation of it on the web but kept coming up with Java and Ruby documention of classes with that name 😆.

**Comment by AliSoftware** [comment]
Interesting. Maybe @JinlianWang, who is the one who implemented the Mocktail support in #108, has more information?

But indeed I'd agree on fixing that and support both formats by checking the presence of a `:` on line 4!

---

As for HTTPMessage that's the format generated by `cur -isl`; so it's a little bit different than Mocktail, but very similar anyway, containing headers then body in a text format. Not sure if it's documented/used widely outside of `curl` though.

**Comment by Ashton-W** [comment]
I might just be misunderstanding Mocktail. This https://github.com/kif-framework/AMYServer framework has th content type on line 4 then header key values on the following lines...

**Comment by JinlianWang** [comment]
Was not aware of the difference. I guess it is better to support both formats.
