### ISSUE TITLE
NSURLSessionTask completion block not called when not following redirects

### ISSUE THREAD

**Issue by adurdin** [AliSoftware/OHHTTPStubs#174]
When `-[NSURLSessionTaskDelegate URLSession:task:willPerformHTTPRedirection:newRequest:completionHandler:]` calls its completion handler with `nil` to indicate that the redirect should not be followed, the completion handler from `-[NSURLSession dataTaskWithRequest:completionHandler:]` is normally called with the actual redirect response itself.

But when using OHTTPStubs such that a stub returns a redirect response, the task’s completion handler is simply never called.

**Comment by AliSoftware** [comment]
Fixed by merging #175 👌
