### ISSUE TITLE
Update wiki entry for OHHTTPStubs_HTTPBody

### ISSUE THREAD

**Issue by AliSoftware** [AliSoftware/OHHTTPStubs#178]
Now that #166 is merged, don't forget to update the [associated wiki entry](https://github.com/AliSoftware/OHHTTPStubs/wiki/Testing-for-the-request-body-in-your-stubs) to relate the new workaround to test that in an easer way now.

\cc @felixLam (don't hesitate to update the wiki entry yourself if you've time before I do btw; otherwise I'll try to do it before a release during this week)

**Comment by AliSoftware** [comment]
@felixLam I updated [the wiki page](https://github.com/AliSoftware/OHHTTPStubs/wiki/Testing-for-the-request-body-in-your-stubs) just now, let me know if you find it clear enough (and if so, you might then close this very issue :wink:)

**Comment by AliSoftware** [comment]
_Tip: you can see the [diff of the wiki page here](https://github.com/AliSoftware/OHHTTPStubs/wiki/Testing-for-the-request-body-in-your-stubs/_compare/62888fefe1242c3a6ea24981b2f30dbc4124dc48...0ead2658f5217d14de55c2f0f6162aa9c7b9bc27) for easier comparison/revision_

**Comment by AliSoftware** [comment]
@shagedorn I'd love if you could take 2 minutes to proof-read the changes in the wiki entry so we can close this one as well!

Thanks for your efforts on this feature btw 👍

**Comment by shagedorn** [comment]
👍 

Should we mention the (quite obvious) caveat that was mentioned in the original PR?

> One known issue is that if you set the HTTPBody and later reset it to nil (for whatever reason), OHHTTPStubs_HTTPBody will still return the last non-nil value.

We could probably fix this by providing an additional reset method, but I don't think it would be of much use.

**Comment by AliSoftware** [comment]
Ah, great point. I agreed providing a reset method is not worth it imho, but we could definitely mention it in the wiki.

**Comment by AliSoftware** [comment]
Note added (under the workaround example). Closing now, thanks for the review!
