### ISSUE TITLE
can not find responseWithJSONObject:statusCode:headers: in OHHTTPStubsResponse

### ISSUE THREAD

**Issue by hemster** [AliSoftware/OHHTTPStubs#181]
Installed through CocoaPods, Use with AFNetworking 2.6.3

**Comment by AliSoftware** [comment]
Which subspec did you list in your `Podfile`? Did you include `pod 'OHHTTPStubs/JSON'`?

**Comment by hemster** [comment]
@AliSoftware nope, just pod 'OHHTTPStubs'. I thought it include all

**Comment by AliSoftware** [comment]
It includes all but the Swift subspec so if you're only using it from ObjC you should be OK on that front.

Did you import the header then (preferably with modular import)? What's your actual code?

**Comment by hemster** [comment]
Ha! You are right, I forgot to import the header.

I only imported
```objc
#import "OHHTTPStubs.h"
```
but not include
```objc
#import "OHHTTPStubsResponse+JSON.h"
```

**Comment by AliSoftware** [comment]
You should use modular imports instead (`@import OHHTTPStubs;`) which imports the whole module that would have avoided you the trouble :wink:

**Comment by hemster** [comment]
Cool! You rock!

**Comment by hemster** [comment]
@AliSoftware  I tried '@import OHHTTPStubs;'  , but it is not working properly. Xcode said module not found. QAQ

**Comment by mikelupo** [comment]
What about 
import <OHHTPStubs/OHHTTPStubs.h>

**Comment by hemster** [comment]
@mikelupo not working, still `OHHTPStubs/OHHTTPStubs.h` _file not found_
