### ISSUE TITLE
Version 5.0.1 sets "Embedded Content Contains Swift Code"

### ISSUE THREAD

**Issue by HHuckebein** [AliSoftware/OHHTTPStubs#186]
It seems that from version 5.0.0 to 5.0.1 the flag is set true now, wich forces the include of all swift standard libraries?!
Which is somehow suboptimal if the main project already includes all standard libraries.

**Comment by AliSoftware** [comment]
Interesting issue! Sorry not to have given any feedback sooner.

I'm wondering if the solution is as simple as just turn `Embedded Content Contains Swift` to `NO` and it will work in all 4 cases (both for people using OHHTTPStubs thru CocoaPods without the Swift subspec, thru CocoaPods and with the Swift subspec, as a framework and using Carthage) though?

**Comment by HHuckebein** [comment]
That is what I did. don't know how it works out with cocoapods. 

Von meinem iPhone gesendet

**Comment by MattesGroeger** [comment]
Currently struggeling with the same issue. Trying to submit our app to the appstore crashes Xcode. The reason being that OHHTTPStubs includes not just the headers but also the standard library.

**Comment by AliSoftware** [comment]
Fixed by #217 / #220 sorry it took so long
