### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by Dershowitz011** [AliSoftware/OHHTTPStubs#189]
Please consider opening a different branch for swift 3. It'd be really helpful. Thanks! :)

**Comment by mxcl** [comment]
You can use my fork for now: https://github.com/mxcl/OHHTTPStubs/tree/swift-3.0

**Comment by AliSoftware** [comment]
@Dershowitz011 I'm gonna close this issue now as you can use either @mxcl 's fork, or use #192.

I'll try to find time soon to merge #192 and make it part of the official repo in master, sorry for the delay!
