### ISSUE TITLE
Can't seem to catch NSURLSession request

### ISSUE THREAD

**Issue by mikelupo** [AliSoftware/OHHTTPStubs#191]
I have a case where we are testing a framework we are writing. 
Our framework is linked into a Host test application (let's call it HostApp).

In the XCode Project we have:
HostApp target 
UnitTest Target

in XCode, General Settings:
The UnitTest Target, we are indeed referencing HostApp in the "Host Application" field.

In XCode build Phases:
Only the UnitTest Target depends on the OHHTTPStubs project, (we build it on the fly) and then links OHHTTPStubs static lib.

in my unit test (test001) I set a stub to catch all requests (just so I can set a breakpoint and examine them for the sake of this exercise).

For non NSURLSession requests coming out of the HostApp I catch all requests with no problem. OHHTTPstubs works as advertised.

Now, for testing NSURLSession requests that are handled by the HostApp, this is where things get muddy.
The NSURLRequest is made by from within the test001.
It looks something like this. 
```
-(void) test001 {

		__weak id<OHHTTPStubsDescriptor> myStub = [AppOHHTTPStubsClass stubRequestsPassingTest:^BOOL(NSURLRequest *request) {
		NSLog(@"-----------> BREAKPOINT FOR: %@", request.URL.absoluteString);
		return N0; //never really stub the return.
	} withStubResponse:^OHHTTPStubsResponse *(NSURLRequest *request) {

		NSMutableDictionary *reqHeaders = [request.allHTTPHeaderFields mutableCopy];
		return [OHHTTPStubsResponse responseWithFileAtPath:OHPathForFile(@"SomethingInMyBundle.mp4", self.class) statusCode:200 headers:reqHeaders];
	}];

	myStub.name = NSStringFromSelector(_cmd);

	[OHHTTPStubs onStubActivation:^(NSURLRequest * _Nonnull request, id<OHHTTPStubsDescriptor>  _Nonnull stub, OHHTTPStubsResponse * _Nonnull responseStub) {
		NSLog(@"~~~~~~~~~~~~~~~~~~~  %@ stubbed by %@.", request.URL, stub.name);
	}];

    //Now that the stub is set up, perform the NSURLSession request.
    NSURLSessionConfiguration *sessionConfig = [NSURLSessionConfiguration defaultSessionConfiguration];
	[MyServiceFactory setupSessionConfiguration:sessionConfig];

	NSMutableDictionary *mDictionary = [NSMutableDictionary new];
	[mDictionary setValue:@"no-store, no-cache" forKeyPath:@"Cache-Control"];
	NSURLSession *session = [NSURLSession sessionWithConfiguration:sessionConfig delegate:self.delegate delegateQueue:nil];

	NSURL *requestURL = [NSURL URLWithString:@"http://www.biplanes.net/crashproof/"];
	NSMutableURLRequest *mRequest = [NSMutableURLRequest requestWithURL:requestURL];
	[mRequest setAllHTTPHeaderFields:mDictionary];

	NSURLSessionDataTask *dataTask = [session dataTaskWithRequest: mRequest];
	[dataTask resume];

}
```

Despite the fact that the request is crafted in the test case (test001), the handling of this request is actually (magically by Apple) done inside the HostApp by our framework. I can see this by setting a breakpoint in the framework. When we stop at the breakpoint I can see the request to http://www.biplanes.net/crashproof.

The Problem:
OHHTTPStubs does not catch this particular request as it goes out.

I tried solving this by linking OHHTTPStubs framework to the HostApp and then referencing the class from HostApp's bundle and setting up a different stub on that class.
like this:
```
Class AppOHHTTPStubsClass = [[NSBundle mainBundle] classNamed:@"OHHTTPStubs"];

__weak id<OHHTTPStubsDescriptor> myAppStub = [AppOHHTTPStubsClass stubRequestsPassingTest:^BOOL(NSURLRequest *request) {
		NSLog(@"-----------> APP STUB BREAKPOINT FOR: %@", request.URL.absoluteString);
		return N0; //never really stub the return.
	}  ...the rest of this method omitted for brevity.

```
This didn't work either. 
What am I doing wrong?

Sorry this isn't as brief as I'd like it to have been but I think I needed to make it as clear and accurate as possible to get the best possible help.

Mike

**Comment by mikelupo** [comment]
Update: Today I learned that the developers had implemented a clever workaround to prevent recursion between the Apple networking libs and our app. This had the unintended side-effect of hiding the request from OHHTTPStubs. As a test, I disabled that clever thing and viola! I can see the requests and respond with a proper mock. 

Closing ...

**Comment by Ashton-W** [comment]
Glad you worked it out anyway @mikelupo

**Comment by AliSoftware** [comment]
:+1: thx for the feedback
