### ISSUE TITLE
About OHHTTPStubs.framework.zip

### ISSUE THREAD

**Issue by hongxinhope** [AliSoftware/OHHTTPStubs#193]
In the latest release version, the framework has been packaged as a zip file.

For ```carthage update```, it's terrible to download a 29MB file in China because of the GFW. 

Any method to improve that?

**Comment by AliSoftware** [comment]
Thx for your issue.

You can simply use `carthage update --no-use-binaries` to tell Carthage not to download the ZIP containing the pre-build binaries but build from source instead.

That's a Carthage-related issue more than an OHHTTPStubs issue btw, as Carthage recommend to create those zip frameworks for those interested, and you can opt-out of it if needed with `--no-use-binaries` anyway (see Carthage's README), while not having those zip files don't offer the alternative for those interested by it.
