### ISSUE TITLE
Multiple test case failed in swift-3.0 branch

### ISSUE THREAD

**Issue by JackieQi** [AliSoftware/OHHTTPStubs#196]
@AliSoftware I tried to run unit test. However, there are several test case failed. Could you please take a look?

**Comment by AliSoftware** [comment]
Thanks for reporting, will try to take a look when I have some more spare time :)

\cc @mxcl @Liquidsoul

**Comment by AliSoftware** [comment]
@JackieQi wait, I was curious about which tests were failing so I still took the test of at least opening the project in Xcode 8b6 on the swift-3 branch and hit Cmd-U… and all the iOS Fmk tests are passing locally.

What version of Xcode 8 are you using? Which tests are failing on your end?

<img width="1851" alt="Xcode8b6-Swift3-AllTestsPass" src="https://cloud.githubusercontent.com/assets/216089/17871739/272aa546-68bd-11e6-89d0-b9e62cd57ce4.png">

**Comment by JackieQi** [comment]
I am using the latest. see the screenshot. Weird though.
![screenshot](https://cloud.githubusercontent.com/assets/358367/17872980/cfad4bd8-6877-11e6-82bb-602df2e4ded5.png)

**Comment by AliSoftware** [comment]
For unit tests related to timing my time tolerance is a bit too short depending on the machine on which you run the tests.

Maybe try running only the tests which failed one by one or increasing the time tolerance in the tests code to see if it solves it.

**Comment by JackieQi** [comment]
@AliSoftware You are absolutely right. All the failed tests are about  kResponseTimeTolerence. So i tweaked them and all passed. Thanks very much for quick response.

**Comment by AliSoftware** [comment]
Thanks for the feedback. I'm closing this now; but if you feel like making a PR to increase the tolerance it might be helpful for others!
