### ISSUE TITLE
Stub cannot catch NSURLSession requests when used with custom protocolClasses

### ISSUE THREAD

**Issue by mikelupo** [AliSoftware/OHHTTPStubs#200]
When an app that is making NSURLSession requests sets a value to the optional config.ProtocolClasses array, OHHTTPStubs cannot catch the request, thus it also cannot reply with the stubbed response.

Can OHHTTPStubs even do anything about this? 

Snip of app code that's initializing the NSURLSession
```
NSURLSessionConfiguration *config;
    config = [NSURLSessionConfiguration defaultSessionConfiguration];

	// You have to explicitly configure the session to use your own protocol subclass here
	// otherwise you don't see redirects <rdar://problem/17384498>.
	config.protocolClasses = @[[CustomURLProtocol class]]; // <---- the offending line. Remove it and OHHTTPStubs works.
```

**Comment by AliSoftware** [comment]
Yes, just use the dedicated method `[OHHTTPStubs setEnabled:YES forSessionConfiguration:config];` to activate the stubs on your custom configuration (and before creating the `NSURLSession` with it)

**Comment by AliSoftware** [comment]
Or even better, don't *set* the `protocolClasses` property to a new value replacing the old one, but instead *add* your `[CustomURLProocol]` to the existing value.
