### ISSUE TITLE
Needs @discardableResult added to func stub

### ISSUE THREAD

**Issue by mrkite** [AliSoftware/OHHTTPStubs#202]
Xcode 8 throws tons of warnings along the lines of "Result of call to 'stub(condition:response:)' is unused".

Since ignoring the return value is totally fine if you don't intend to call removeStub, you should mark the function with @discardableResult and save us from the warning spam.

**Comment by Ashton-W** [comment]
What Seift versions are compatible with that annotation?

A Pull Request would be great :)

**Comment by ikesyo** [comment]
> What Swift versions are compatible with that annotation?

`@discardableResult` is for Swift 3.

**Comment by AliSoftware** [comment]
Closing this as it's been addressed a while ago by #203 :wink:
