### ISSUE TITLE
enhancement - Support for HAR files / HTTP Archives

### ISSUE THREAD

**Issue by johndpope** [AliSoftware/OHHTTPStubs#204]
This project can quickly read and parse HAR files. 
https://github.com/johndpope/HAR-Reader

Saving from charles -> 
https://gist.github.com/jjarava/5f26806bba75d052c41a

The HAR spec is basically json.

**Comment by AliSoftware** [comment]
Seems like an interesting idea! Would probably not have much time implementing that soon though, but would love a PR for that!

**Comment by johndpope** [comment]
I'm getting really good mileage using SWHttpTrafficRecorder 

#import <SWHttpTrafficRecorder/SWHttpTrafficRecorder.h>

    [SWHttpTrafficRecorder sharedRecorder].recordingFormat =  SWHTTPTrafficRecordingFormatBodyOnly;
    NSArray *documentPath = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
    NSString *docs = [documentPath objectAtIndex:0];
    NSString *path = [docs stringByAppendingPathComponent:@"yourLoggingDir"];
    
    [[SWHttpTrafficRecorder sharedRecorder] startRecordingAtPath:path error:nil];

**Comment by johndpope** [comment]
Ok - here we go.
https://github.com/johndpope/HAR-Reader/blob/master/HarReader/AppDelegate.swift

**Comment by AliSoftware** [comment]
I'm not sure I understand what you want me to do with that?

* Should that be a new feature of OHHTTPStubs?
* Should it be an additional example project linked in the wiki page?
* Should it be a link we add in the wiki to your gist, using it as a blog-posty documentation?
* Should it be converted into a dedicated wiki page on my repo explaining how to read HAR files?
* Or does it needs us to add a new subspec in OHHTTPStubs to allow people to parse HAR files easily?

I'm quite confused with what you expect me to do with your links there tbh ;)

**Comment by johndpope** [comment]
I built a class that takes a HAR file - and will automatically stub entire payload via OHHTPStubs.
Albeit it's in swift. It will even mock the server response codes.

HARStub.stubHarFile(fileName: "openlab.har")

so given a charles capture - it will play back everything as if the internet existed without being online.

I think the intention of ohhtpstubs was to do this and all - this is cleaner - provides a snapshot of api for stable developent - allows drag and drop traffic playback from charles captures.


I think people will want to use this or I'm also building another plist to load json given a url. 
This is a must have 1 liner. Please consider exposing feature in main project. 
It doesn't need to be a subspec. 


I'm building out in my app to provide in flight switching of different environments using AppConfigSwift https://raw.githubusercontent.com/wwe-johndpope/AppConfigSwift/master/Images/AppConfigSwift.gif

**Comment by AliSoftware** [comment]
So… basically adding a dedicated page in [OHHTTPStubs' wiki](https://github.com/AliSoftware/OHHTTPStubs/wiki) like "Using HAR files with CharlesProxy to configure all stubs easier", to explain how using Charles and a HAR file and you class could help people? And then link to that wiki page in the README?

**Comment by johndpope** [comment]
that'd work - I don't suppose you can / or want to mix swift with cocoapod library. 
probably really really bad idea.

**Comment by johndpope** [comment]
spring cleaning my github issues - 56 to go. 
Thanks for your efforts here @AliSoftware
