### ISSUE TITLE
dynamicType deprecated - OHPathForFile

### ISSUE THREAD

**Issue by AJ9UNiDAYS** [AliSoftware/OHHTTPStubs#207]
In the usage example:

```
// Swift
stub(isHost("mywebservice.com")) { request in
  // Stub it with our "wsresponse.json" stub file
  return OHHTTPStubsResponse(fileAtPath:OHPathForFile("wsresponse.json", self.dynamicType)!
    statusCode:200 headers:["Content-Type":@"application/json"])
}];
```

Using Xcode 8 with Legacy Swift enabled I'm unable to compile `self.dynamicType`

Xcode suggests using `type(of:...)` but I can't seem to get this to work.

**Comment by Liquidsoul** [comment]
Hi @AJ9UNiDAYS !

This should work, or maybe something broke with the Xcode 8 release 😅
What depency manager do you use to integrate `OHHTTPStubs`?

**Comment by AJ9UNiDAYS** [comment]
I was using Cocoapods, I suspect it may be an Xcode 8 glitch. I've had to rollback to using Swift 2.3 and Xcode 8 where this isn't an issue. May pop up again in anyone using a pure Swift 3.0 project?

**Comment by Liquidsoul** [comment]
Sorry for not getting back to you sooner.
I think this is related to Cocoapods and Xcode 8.0. See this other issue #209 
Feel free to comment / reopen if this is not the case.
