### ISSUE TITLE
Xcode 8 says the files are not Swift 3.0 in version 5.2.1

### ISSUE THREAD

**Issue by cbauer10** [AliSoftware/OHHTTPStubs#209]
The newest version is giving errors that it is not Swift 3.0 although the CHANGELOG.md claims it is Xcode 8 Swift 3.0 compatible.

**Comment by Liquidsoul** [comment]
Hi @cbauer10,
Thank you for your feedback !

Could you give us some details on the errors you have? And how the library is integrated in your project?

Thanks !

**Comment by svachmic** [comment]
Same here. As noted below:

<img width="1084" alt="screen shot 2016-09-20 at 15 38 32" src="https://cloud.githubusercontent.com/assets/1448888/18672409/5dcb27d2-7f48-11e6-953e-30674ab1338d.png">

My setup is:

* Xcode Version 8.0 (8A218a)
* CocoaPods 1.0.1

Podfile:

>platform :ios, '9.0'
>use_frameworks!
>
>target "Gigsterous" do
>> pod 'OHHTTPStubs'
>> pod 'OHHTTPStubs/Swift'
>
>end

Console output while **pod install**:

> Installing OHHTTPStubs (5.2.1)
> Generating Pods project

Hope it helps, looking forward to using it again! 👍

**Comment by ikesyo** [comment]
You should update to CocoaPods 1.1.0 (currently rc2) to be used with Xcode 8: `gem update cocoapods --pre`.

**Comment by svachmic** [comment]
@ikesyo  It did help indeed! Thanks a lot!

**Comment by cbauer10** [comment]
@ikesyo Glad to know that the fix is coming.  I just can't work with pre-release code at my company.  You don't have any insight as to when it will be released do you?

**Comment by AliSoftware** [comment]
CocoaPods 1.1.0 is coming very soon. Just a couple of PRs to finish to be sure not handle every possible tricky Xcode8/Swift3 complex configurations out there.

CP 1.1.0.rc.2 is super stable enough though, no reason to not use it. CP is not in beta anymore, and we use the RC at work without any problem.

Gonna close this issue now as it's silver by latest CP, and is not an OHHTTPStubs issue itself anyway.
