### ISSUE TITLE
Add a github issue template to the project

### ISSUE THREAD

**Issue by Liquidsoul** [AliSoftware/OHHTTPStubs#210]
I think that it could be nice to have some standard way of formatting an issue with some basic information to fill for the reporter (like the installation method) or to check before submitting the issue.

**Comment by AliSoftware** [comment]
+ :100:

**Comment by Ashton-W** [comment]
What do you think about checkboxes in the issue template, like fastlane/fastlane

**Comment by AliSoftware** [comment]
I think a mix of checkboxes (for a checklist of what people have to ensure before creating an issue) and a markdown template (with various sections to fill by the user) could be perfect

**Comment by AliSoftware** [comment]
Implemented in #241
