### ISSUE TITLE
Carthage version problem for swift 3.0 Xcode 8.0

### ISSUE THREAD

**Issue by gauravds** [AliSoftware/OHHTTPStubs#211]
Unable to get the update for swift 3.0
Getting this error every time.

`ld:  ...../Carthage/Build/iOS/OHHTTPStubs.framework/OHHTTPStubs compiled with older version of Swift language (2.0) than previous files (3.0) for architecture x86_64`

Cartfile
`github "AliSoftware/OHHTTPStubs" ~> 5.2.1`

Command run
`$ carthage update --platform iOS`

How to solve this issue for carthage download?

**Comment by Liquidsoul** [comment]
Hi @gauravds !

You need to specify the `swift-3.0` branch of `OHHTTPStubs` in your Cartfile if you use Swift 3.0.
The latest release is still set to compile in Swift 2.3.
See [this section](https://github.com/AliSoftware/OHHTTPStubs/blob/master/README.md#using-the-right-swift-version-of-ohhttpstubs-for-your-project) in the README.
