### ISSUE TITLE
Using with Google Maps iOS SDK

### ISSUE THREAD

**Issue by zachlucas** [AliSoftware/OHHTTPStubs#219]
I'm trying to stub my Google Places calls using a local `json` file.  Using Charles proxy, I find that the Google Maps SDK uses the url `https://www.googleapis.com`.  So, I try to stub like:

```
stub(isHost("https://www.googleapis.com")) { request in
   OHHTTPStubsResponse(fileAtPath: "google_maps.json", statusCode: 200, headers: ["Content-Type":"application/json"])
}
```

But it's not intercepting the google maps SDK calls.  Any ideas?  Could this be the Google Maps SDK using something other than Cocoa's URL Loading System?

**Comment by AliSoftware** [comment]
`https://www.googleapis.com"` is not a host. That a full URL. The host of this URL (as returned by `NSURL(string: "https://www.googleapis.com")!.host` for example) is just `www.googleapis.com`.

**Comment by zachlucas** [comment]
Thank you, that was my issue.
