### ISSUE TITLE
pathStartsWith when missing a leading '/'

### ISSUE THREAD

**Issue by KingOfBrian** [AliSoftware/OHHTTPStubs#223]
I was using `pathStartsWith`, and couldn't get things to work. Turned out that I didn't have a leading '/'. I don't think `pathStartsWith` will ever work if it's missing a leading '/'. Would it make sense to insert a leading '/' , or assert if the path doesn't have the '/' prefix? I'd gladly whip up a PR if it was of interest.

**Comment by AliSoftware** [comment]
Even if they are very rare, I think there might exist URL paths not starting with `/`, like `foo:bar` (which is a valid URI iinm?), so not sure we should enforce this for everybody?

**Comment by KingOfBrian** [comment]
Yea, looks like URIs with no host can do that, and since the predicate has no context you can't be sure. Oh well!
