### ISSUE TITLE
Proposal for Swift: hasBody OHHTTPStubsTestBlock

### ISSUE THREAD

**Issue by Antondomashnev** [AliSoftware/OHHTTPStubs#228]
Hi there,

I'm not sure if there was the same idea already or not. But what do you think about adding new  `OHHTTPStubsTestBlock`.

```swift
public func hasBody(_ body: Data) -> OHHTTPStubsTestBlock {
    return { req in req.OHHTTPStubs_HTTPBody? == body }
}
```

I see the problem here, that the `Swift` subspec doesn't contain the `URLSession` subspec by default, which makes sense. But maybe it could a new one `SwftURLSession` or something like that?

In the end, I find this new test block very useful. And I'd love to add this in PR if the feature is approved 🚀

**Comment by AliSoftware** [comment]
That seems like a good idea. I'm starting more and more to consider including `URLSession` and `JSON` subspecs as part of the `Swift` subspec by default. If we do that, we could merge your idea in :wink:

**Comment by Antondomashnev** [comment]
@AliSoftware do you have any estimation to decide whether to merge subspecs or not? Could you please point the cons of merging? 😄

**Comment by AliSoftware** [comment]
Main con of merging is inability to opt *out*.
Will try to make time for it this week

**Comment by AliSoftware** [comment]
@Antondomashnev  #242 will _finally_ (!) solve this and make `hasBody` part of the Swift API! 🎉

**Comment by Antondomashnev** [comment]
@AliSoftware wow, that's an amazing news 🎉 🚀
