### ISSUE TITLE
enhancement - Wildcard in path

### ISSUE THREAD

**Issue by Reedyuk** [AliSoftware/OHHTTPStubs#235]
Hi,
I cannot seem to find a way to match my urls with a wildcard.
For example:
`/hello/9ff49154-9a63-460a-b63a-50b74ded4161/anotherMethod`

I would usually pass something like:
`/hello/*/anotherMethod`

To match the method, as this is how the api structure is setup.

**Comment by AliSoftware** [comment]
I'll close this issue as a duplicate of #125, please continue any discussion there.
