### ISSUE TITLE
Update to 3.1

### ISSUE THREAD

**Issue by cohilla** [AliSoftware/OHHTTPStubs#237]
Please convert the source code to Swift 3.1 syntax, so that we can use with Xcode 8.3.

When trying to rebuild the framework:

`Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/cghill/carthage/Carthage/Checkouts/OHHTTPStubs/OHHTTPStubs/OHHTTPStubs.xcworkspace -scheme "OHHTTPStubs iOS Framework" -configuration Release -derivedDataPath /Users/cghill/Library/Caches/org.carthage.CarthageKit/DerivedData/OHHTTPStubs/5.2.3 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build`
...
`“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.`

**Comment by AliSoftware** [comment]
Could you maybe submit a Pull Request? I'm a bit behind with all my open-source projects so any help is appreciated and would help make the migration happen faster :wink:

**Comment by AliSoftware** [comment]
BTW, I'm not sure we'd have to change much between what's already in the `swift-3.0` branch and what's needed to make that Swift 3.0 branch compile in Swift 3.1?

(I plan to make that swift-3.0 branch the default (replacing master) one day, just still haven't had the time yet)

**Comment by Liquidsoul** [comment]
Hi @cohilla,

I think your issue is related to #233,
If you use Carthage, you must use `-swift3` suffixed releases (in your case `5.2.2-swift3`) until we make `master` use Swift 3.0.
Do not despair, we are working on it #240 😉

**Comment by cohilla** [comment]
I'm able to build using Carthage and the Xcode-8.3 branch 👍 

I will close this since another issue is open to update the master branch.
