### ISSUE TITLE
weird behavoir

### ISSUE THREAD

**Issue by wassimseif** [AliSoftware/OHHTTPStubs#246]
### New Issue Checklist

- [x] I have tried with the latest version of OHHTTPStubs
- [x] I have read the [README](https://github.com/AliSoftware/OHHTTPStubs/blob/master/README.md)
- [x] I have read the [Using the right Swift Version of `OHHTTPStubs` for your project](https://github.com/AliSoftware/OHHTTPStubs#using-the-right-swift-version-of-ohhttpstubs-for-your-project) section
- [x] I have searched in the [existing issues](https://github.com/AliSoftware/OHHTTPStubs/issues?utf8=✓&q=is%3Aissue)
- [ ] I have read [the OHHTTPStubs wiki](https://github.com/AliSoftware/OHHTTPStubs/wiki) to see if there wasn't a detailed page talking about my issue

### Environment

- version of OHHTTPStubs: [LIB VERSION HERE]
- integration method you are using:
  * [x] Cocoapods
  * [ ] Carthage
  * [ ] submodule
  * [ ] other
- version of the tool you use: 1.2.0

### Issue Description
Not stubbing even though condition is true 

##### Complete output when you encounter the issue (if any)

```
 func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        
        let condition : OHHTTPStubsTestBlock = { (request : URLRequest) in
            if request.url!.host == "localhost"{
                print("true")
                return true
            }
            print("false")
            return false
        }
        
        stub(condition: condition ) { _ in
            print("Stubbing")
            return OHHTTPStubsResponse()
        }

        return true
        
    }

```
The condition is always true but the `print("Stubbing") never runs 
`

**Comment by AliSoftware** [comment]
Hi 

Are you saying that the `print("true")` is executed and shows up in your console but the `print ("Stubbing")` doesn't?

Did you try with anything other than localhost?
I'm thinking maybe the iOS URL Loading System treats localhost as a special case and doesn't ask NSURLProtocol chain in those cases or bypass the system?

**Comment by wassimseif** [comment]
Yes that's exactly what happened. Now i changed it to 
```
 func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        
        let condition : OHHTTPStubsTestBlock = { (request : URLRequest) in
            if request.url!.host! == "www.mocky.io"{
                print("true")
                return true
            }
            print("false")
            return false
        }
        
        stub(condition: condition ) { _ in
            print("Stubbing")
            return OHHTTPStubsResponse()
        }

        return true
        
    }

```
and still nothing changes. prints true all the time but never prints stubbing

**Comment by wassimseif** [comment]
I'm using `Alamofire`

**Comment by wassimseif** [comment]
Okay i think i knew what wrong. When using a `RxSwift` wrapper around `Alamofire` it doesn't work. i think due to asynchronous calls? when sending the request like this 
```
  Alamofire.request("http://www.mocky.io/v2/590c43ed270000d70ab2a7ca").responseJSON { response in
        
        
        
        
        }
```
it works! 
is thiss doable using an `RxSwift` wrapper around `Alamofire`

**Comment by AliSoftware** [comment]
What's the Rx wrapper you are using?
At my company we use a custom-made Rx wrapper around Alamofire too (and not the RxAalmofire pod) and it works as expected…

Maybe you're creating your `Alamofire.SessionManager` too early, so before `OHHTTPStubs` has time to swizzle and inject the stubs protocol before the `NSURLSession.configuration` has time to be created?

**Comment by wassimseif** [comment]
It's a really simple wrapper that doesn't affect the manager. Here is it 
```
extension DataRequest{
    
    public func processMap<N>(mapObject:@escaping (AnyObject)->N?) -> Observable<N>{
        
        return Observable.create{ (observer) -> Disposable in
            self.responseJSON(completionHandler: { (response : DataResponse<Any>) in
                switch response.result {
                case .success :
                    guard let o = mapObject(response.result.value! as AnyObject) else{
                        observer.on(Event.error(ObjectMapError.MapError(response.result.value as? JSON)))
                        return
                    }
                    observer.on(Event.next(o))
                    
                case .failure :
                    observer.on(Event.error(ObjectMapError.APIResponseError(response.result.value as? JSON)))
                }
            })
            return Disposables.create {
                self.cancel()
            }
        }
    }
    
    public func rx_responseArray<T:Mappable>(type:T.Type) -> Observable<[T]>{
        return self.processMap(mapObject: { (json) in
            Mapper<T>().mapArray(JSONArray: json as! [JSON])
            
        })
    }
    
    public func rx_responseObject<T:Mappable>(type:T.Type) -> Observable<T>{
        return self.processMap(mapObject: { (json) in
            Mapper<T>().map(JSON: json as! [String : Any] )
            
        })
    }
}
```

If you want you can test it. Here's link for the wrapper https://github.com/wassimseif/rxalamofiremapper

**Comment by AliSoftware** [comment]
Strange indeed.
I'm not sure I'll have much time to look at in very soon, as I have quite some work and also talks to prepare. So what I can propose you is:

 - Compare your code with our own wrapper we use: [NetworkStack](https://github.com/NijiDigital/NetworkStack) — maybe you'll find some differences and see what would make ours work but not yours and get some inspiration from that?
 - Hope someone will have time to take a look at your problem (@Liquidsoul ?) before I have more free time myself
 - Ping me in a week or two if you didn't have any progress on the issue, I might have some more time by then

**Comment by Liquidsoul** [comment]
Hi @wassimseif 

Thanks again for reporting your issue!

You are saying here that you are using Cocoapods to integrate `OHHTTPStubs` but your wrapper `rxalamofiremapper` does not seem to use Cocoapods but Carthage.  
Does this mean that you are using _both_ dependency managers in your project?

I tried to use your wrapper but failed to do so in a test App because it lacks a shared scheme needed by Carthage to build the framework (I tried the latest version and the `master` branch).  
I am afraid I will not be able to reproduce your issue and help you out unless you give us a configured project exposing the problem 😞

BTW, your issue seems to be missing the version of Cocoapods you are using and the `OHHTTPStubs` one (6.0.0) is not in the correct spot. Could you edit your issue to confirm these informations please? ☺️

**Comment by wassimseif** [comment]
Hello @Liquidsoul 
Thank you for your time to lookup the issue. I have updated the issue. I'm using `Cocoapods 1.2.0` to install `OHHTTPStubs ` version `6.0.0`. For the wrapper, I'm not using any dependency manager to install it, just by copying the files to my project. Since the wrapper requires `RxSwift` 
 and `Alamofire`. I'm also using `Cocoapods` to install them. Hears the output of my Podfile.lock 
```
PODS:
  - Alamofire (4.4.0)
  - Nimble (6.0.1)
  - ObjectMapper (2.2.6)
  - OHHTTPStubs/Core (6.0.0)
  - OHHTTPStubs/Default (6.0.0):
    - OHHTTPStubs/Core
    - OHHTTPStubs/JSON
    - OHHTTPStubs/NSURLSession
    - OHHTTPStubs/OHPathHelpers
  - OHHTTPStubs/JSON (6.0.0):
    - OHHTTPStubs/Core
  - OHHTTPStubs/NSURLSession (6.0.0):
    - OHHTTPStubs/Core
  - OHHTTPStubs/OHPathHelpers (6.0.0)
  - OHHTTPStubs/Swift (6.0.0):
    - OHHTTPStubs/Default
  - Quick (1.1.0)
  - Realm (2.6.2):
    - Realm/Headers (= 2.6.2)
  - Realm/Headers (2.6.2)
  - RealmSwift (2.6.2):
    - Realm (= 2.6.2)
  - RxBlocking (3.4.0):
    - RxSwift (~> 3.4)
  - RxCocoa (3.4.0):
    - RxSwift (~> 3.4)
  - RxSwift (3.4.0)
  - RxTest (3.4.0):
    - RxSwift (~> 3.4)
  - SWHttpTrafficRecorder (1.0.2)
  - SwiftEventBus (2.2.0)
  - Swinject (2.1.0)

DEPENDENCIES:
  - Alamofire (~> 4.4)
  - Nimble
  - ObjectMapper (~> 2.2)
  - OHHTTPStubs/Swift
  - Quick
  - RealmSwift
  - RxBlocking (~> 3.0)
  - RxCocoa (~> 3.0)
  - RxSwift (~> 3.0)
  - RxTest (~> 3.0)
  - SWHttpTrafficRecorder
  - SwiftEventBus (from `https://github.com/cesarferreira/SwiftEventBus.git`, tag `2.2.0`)
  - Swinject (~> 2.1.0)

EXTERNAL SOURCES:
  SwiftEventBus:
    :git: https://github.com/cesarferreira/SwiftEventBus.git
    :tag: 2.2.0

CHECKOUT OPTIONS:
  SwiftEventBus:
    :git: https://github.com/cesarferreira/SwiftEventBus.git
    :tag: 2.2.0

SPEC CHECKSUMS:
  Alamofire: dc44b1600b800eb63da6a19039a0083d62a6a62d
  Nimble: 1527fd1bd2b4cf0636251a36bc8ab37e81da8347
  ObjectMapper: '042708195cc46c20871cbcbec0453826398273fd'
  OHHTTPStubs: 752f9b11fd810a15162d50f11c06ff94f8e012eb
  Quick: dafc587e21eed9f4cab3249b9f9015b0b7a7f71d
  Realm: 29222766425b9f831228f81b63f0e38a97a4d700
  RealmSwift: d161a80f96cb91ae88391a7d5a9cf08024a7bc8e
  RxBlocking: 1797b8c1a3ad7b08965145e6e2294c2e101515aa
  RxCocoa: d14ef6b6029e1ddc6e966508c09289090de68ff9
  RxSwift: 3789a1af753002a14edecdb698a2424624296a9c
  RxTest: beb6beb882cf1dcac5fc9fdbd4760a5254e7f3a6
  SWHttpTrafficRecorder: 6c0804d3f8edf9c7f3a1e0eec9f6bf5e4b241b9f
  SwiftEventBus: 39cde57d1881f9d6e8afb1f9e41f973e331bf847
  Swinject: 85e468ac75c5c2d234076f98c591d57d56bc64bc

PODFILE CHECKSUM: 0caf8a7da8bfb24ce2beb4e76bb04bb2f69177d5

COCOAPODS: 1.2.0

```

**Comment by wassimseif** [comment]
@AliSoftware i checked NetworkStack and it's really interesting. do you have any sample app to demo it?

**Comment by AliSoftware** [comment]
@wassimseif we have a lot of work to do on it it to better document it, make a proper README and examples & demo projects indeed, haven't had that much time for that; but I know there's a pending pull request from one of my colleague adding a lot on that regard: check the "documentation" branch I think he even added sample projects in there

**Comment by mikelupo** [comment]
Maybe you need an asynchronous wait?

**Comment by AliSoftware** [comment]
@wassimseif Any update on this, especially did you indeed ensure that you didn't forget the asynchronous wait in your test (e.g. using `XCTestExpectation` like [explained here in the Wiki](https://github.com/AliSoftware/OHHTTPStubs/wiki/OHHTTPStubs-and-asynchronous-tests))

**Comment by wassimseif** [comment]
@AliSoftware I migrated to the network stack you provided the link for. it's much more mature than the one i wrote.

**Comment by Liquidsoul** [comment]
Cool! Did this solved your issue?
If so, would you mind closing the issue? 😊

**Comment by wassimseif** [comment]
@Liquidsoul Yess. Thank you very much for your help. Awesome people!
