### ISSUE TITLE
Stub not working as expected

### ISSUE THREAD

**Issue by mrjimoy** [AliSoftware/OHHTTPStubs#247]
I tried to initialize unit tests on my project but seems that the stubs not being called. Each time I tried to debug, it always pass the stub's line. Anyone have an idea? Thanks.

**HomeConnectorTests.swift**
```swift
import XCTest
import OHHTTPStubs
import Nimble
@testable import Pods_Mobile_iOS

class HomeConnectorTests: XCTestCase {
    
    override func setUp() {
        super.setUp()

        OHHTTPStubs.setEnabled(true)
        
        OHHTTPStubs.onStubActivation() { request, descriptor, response in
            // ...
        }
    }
    
    override func tearDown() {
        OHHTTPStubs.removeAllStubs()

        super.tearDown()
    }
    
    func testGetHomeData_RequestsDefault_Return200() {
        TestsHelper.stubNetwork(forConnector: HomeConnector.self,
                                   endpoint: "home",
                                   stubFileName: "GET_Home_200")
        
        
        HomeConnector.sharedInstance.getHomeConfig(onSuccess: { (data, object) in
            // --> Not even entering this part
        }) { (data, error) in
            XCTAssertFalse(true)
        }
        
        waitForExpectations(timeout: 10, handler: nil)
    }
    
}
```
**TestsHelper.swift**
```swift
import UIKit
@testable import Pods_Mobile_iOS
import OHHTTPStubs

class TestsHelper: NSObject {
    
    static func stubNetwork(forConnector connector: NSObject.Type, endpoint: String, stubFileName: String) {
        stub(condition: isHost(HttpConnector.sharedFCHTTPClient().getKAPIBaseUrl()) && isPath(endpoint)) { request in
            // --> Not even entering this part also :(
            guard let path = OHPathForFileInBundle(stubFileName.appending(".json"), Bundle.main)
                else {
                    preconditionFailure("Stub not found!")
            }
            
            return OHHTTPStubsResponse(
                fileAtPath: OHPathForFile(path, type(of: self) as! AnyClass)!,
                statusCode: 200,
                headers: ["Content-Type":"application/json"]
            )
        }
    }
    
}
```

This is the connector I use to get the response from the API : 

**HomeConnector.swift**
```swift
class HomeConnector: MainApiConnector {

    static let sharedInstance = HomeConnector()
    
    fileprivate override init() {
        super.init()
    }
    
    func getHomeConfig(onSuccess: @escaping ConnectorSuccessBlock, onFailure: @escaping ConnectorFailureBlock){
        self.makeRequestToAPIEndPoint(endPoint, method: "GET", params: nil, headers: self.getGETHeader() as? Dictionary<String, String>, onSuccess: { (task, responseObject) in
            onSuccess(task, responseObject)
        }) { (task, error) in
            onFailure(task, error)
        }
    }

}
```

**MainApiConnector.swift**
```swift
import AFNetworking

typealias ConnectorSuccessBlock = (URLSessionDataTask?, AnyObject?) -> Void
typealias ConnectorFailureBlock = (URLSessionDataTask?, NSError?) -> Void

@objc open class MainApiConnector : NSObject {

    var parentConnector : HttpConnector

    override init() {
        self.parentConnector = HttpConnector.sharedFCHTTPClient()
    }

    func makeRequestToAPIEndPoint(_ endPoint: String, method: String, params: Dictionary<String, Any>?, headers: Dictionary<String, String>?, onSuccess: @escaping ConnectorSuccessBlock, onFailure: @escaping ConnectorFailureBlock) {
        var url = parentConnector.getKAPIBaseUrl() + "\(endPoint)"
        url = url.replacingOccurrences(of: " ", with: "+")

        // ... (I omit this part as it's not necessary)
    }

}
```

### Environment
- OHHTTPStubs 6.0.0
- Cocoapods 1.0.1
- XCode 8.3.2
- Swift 3

**Comment by Liquidsoul** [comment]
Hi @mrjimoy,

It seems you are missing an XCTestExpectation instance with its corresponding `fulfill` call to match your `waitForExpectations` call.
If you don't have any expectation your test will terminate before the asynchronous call. In fact, in your example, the timeout argument in `waitForExpectations` has no effect.

Here is my suggestion (note that I wrote this without compiling it so this may need some fixes here and there):
```swift
func testGetHomeData_RequestsDefault_Return200() {
        TestsHelper.stubNetwork(forConnector: HomeConnector.self,
                                   endpoint: "home",
                                   stubFileName: "GET_Home_200")
        let successExpectation = self.expectation(description: "success called")
        
        HomeConnector.sharedInstance.getHomeConfig(onSuccess: { (data, object) in
            // --> Not even entering this part
            successExpectation.fulfill()
        }) { (data, error) in
            XCTAssertFalse(true)
        }
        
        waitForExpectations(timeout: 10, handler: nil)
    }
```

**Comment by mrjimoy** [comment]
Hi @Liquidsoul, thank you so much for your reply. I have tried that, now it's entering the closure but I got a response directly from the API, not the json file I provided ("GET_Home_200"). Anything I missed out?

**Comment by Liquidsoul** [comment]
This may mean that your condition is not met.
```swift
isHost(HttpConnector.sharedFCHTTPClient().getKAPIBaseUrl()) && isPath(endpoint)
```

Try removing the condition and enabling the stub for all the requests to check if the stubbing works.

**Comment by mrjimoy** [comment]
But that is something like: 

`HttpConnector.sharedFCHTTPClient().getKAPIBaseUrl()` = `https://api.some.com/`
`endpoint ` = `home`

I tried to change it as:

`isHost(HttpConnector.sharedFCHTTPClient().getKAPIBaseUrl().appending(endpoint))`

but still the same. What should I put there then?

**Comment by AliSoftware** [comment]
@mrjimoy `isHost` compares the string you give with the request's `url.host` property. 
The host part of an URL, as specified in the RFC and in NSURL documentation, is just `api.some.com`, without the "https://" part and without any `/`. While "https" is what is called the "scheme" part of an URL (which you can test via `isScheme("https")` if you wish to)

So that's why your request doesn't gets stubbed. It's because, as @Liquidsoul suggested, the condition for matching your request is always false. Only pass the `isHost("api.some.com")` for the host without the scheme (without the "https://" part nor the trailing slash) to fix it.

**Comment by mrjimoy** [comment]
Hi @AliSoftware, thanks, it works now. Everything will be smooth from now on :)

**Comment by AliSoftware** [comment]
@Liquidsoul  I wonder if we should add a `preconditionFailure(!host.contains("/"), "The host part of an URL never contains any slash. Only use strings like 'api.example.com' for this value, and not things like 'https://api.example.com/'")` in the `isHost` implementation? Or at least add `- Note` entries in the function's doc comments to hint about this?
And probably same for some other test helpers (like `isScheme` isn't supposed to contain the "://" part either, etc)

**Comment by Liquidsoul** [comment]
@AliSoftware yeah, I think that's a good idea. I will try to do submit a PR on this in the coming days.

**Comment by mikelupo** [comment]
I know this isn't a question directed to me but I give +1 to the idea.

**Comment by MrNeekReevers** [comment]
I fell into this same trap with isHost() today. This question solved my issues.

**Comment by AliSoftware** [comment]
I just realized that this has been fixed by triggering an assertion when you misuse isHost (see https://github.com/AliSoftware/OHHTTPStubs/pull/248)… but that I haven't done a release in a while so that fix is still in master but was never officially released!

Will try to do a release soon. Don't hesitate to bump if I forget by next week.
