### ISSUE TITLE
How can i get the request parameters

### ISSUE THREAD

**Issue by VincentDengSZ** [AliSoftware/OHHTTPStubs#249]
i want to  get request parameters ,and response based on parameters

**Comment by AliSoftware** [comment]
Simply inspect the `request` parameter passe to the closure you give when you create your stub:

```swift
stub(isHost("mywebservice.com")) { request in
  let params = request.url!.query // contains your parameters as string like "a=1&b=2&c=3
  // you can also use URL:
  let comps: [URLQueryItems] = URLComponents(url: request.url!, resolvingAgainstBaseURL: true)!.queryItems!
  // then iterate over the comps to check if you have the item.name and item.value you expect
  // then build your response accordingly
  return OHHTTPStubsResponse(…)
}
```
Note that if your parameters are in the body you'll have to use the `request.ohhttpStubs_httpBody` property to get the NSData of the body instead and get back the parameters.

One last solution is to use `NSURLProtocol.setProperty(parameters, forKey:NSURLRequestParametersMetadataKey, inRequest:req]` — see [this entry in our wiki](https://github.com/AliSoftware/OHHTTPStubs/wiki/Testing-for-the-request-body-in-your-stubs#storing-requests-meta-data-to-write-easier-tests) for more info

**Comment by VincentDengSZ** [comment]
Got it . thanks
