### ISSUE TITLE
Stub check endpoint parameter also

### ISSUE THREAD

**Issue by mrjimoy** [AliSoftware/OHHTTPStubs#255]
Hi, is it possible to check stub condition including the parameters using **isPath("")**? Currently I have a code to check only for Host and Endpoint, and for endpoint it works only for something:

- endpoint1
- endpoint2, etc...

What I want to check also is the query params on it, like : `endpoint1/configId=XXX`, or `endpoint1`. Both of them **should** return a different json response based on given stubFileName. Can I achieve that? Thanks..

```
    static func stubNetwork(forConnector connector: NSObject.Type, endpoint: String, stubFileName: String) {
        if let apiBaseURL = URL(string: HttpConnector.sharedFCHTTPClient().getKAPIBaseUrl()),
                let urlHost = apiBaseURL.host {
            stub(condition: isHost(urlHost) && isPath("/".appending(endpoint))) { request in
                guard let path = OHPathForFileInBundle(stubFileName, Bundle.init(for: TestsHelper.classForCoder()))
                    else {
                        preconditionFailure("Stub not found!")
                }
                
                return OHHTTPStubsResponse(
                    fileAtPath: path,
                    statusCode: 200,
                    headers: ["Content-Type":"application/json"]
                )
            }
        }
    }
```

**Comment by AliSoftware** [comment]
You have multiple options there: 

- there's a matcher helper called `containsQueryParams(…)` so you can combine `isHost(…) && isPath(…) && containsQueryParams(…)` and so on 
 - remember that the matcher parameter (the first parameter of the stub method) is actually just a closure taking the request and returning a boolean. Helpers like `isPath(…)` etc are just helper functions to construct closures for common use cases but if you need more control you can always provide a custom closure to fit advanced needs. 

In your use case you could also either:
- prefer install two different stubs with 2 different conditions (one with some `containsQueryParams(xx)` and another with `containsQueryParams(yy)`) 
- or stub all request, and return a different value in the trailing closure (using a simple `if`) depending on `req.url?.query` or similar 

So really you have a lot of options to do that!

**Comment by mrjimoy** [comment]
Wow okay, will try that! Thanks for the suggestion @AliSoftware :)
