### ISSUE TITLE
Swift 4 Support

### ISSUE THREAD

**Issue by eman6576** [AliSoftware/OHHTTPStubs#257]
### New Issue Checklist

- [x] I have tried with the latest version of OHHTTPStubs
- [x] I have read the [README](https://github.com/AliSoftware/OHHTTPStubs/blob/master/README.md)
- [x] I have read the [Using the right Swift Version of `OHHTTPStubs` for your project](https://github.com/AliSoftware/OHHTTPStubs#using-the-right-swift-version-of-ohhttpstubs-for-your-project) section
- [x] I have searched in the [existing issues](https://github.com/AliSoftware/OHHTTPStubs/issues?utf8=✓&q=is%3Aissue)
- [x] I have read [the OHHTTPStubs wiki](https://github.com/AliSoftware/OHHTTPStubs/wiki) to see if there wasn't a detailed page talking about my issue

### Environment

- version of OHHTTPStubs: [LIB VERSION HERE]
- integration method you are using:
  * [x] Cocoapods
  * [ ] Carthage
  * [ ] submodule
  * [ ] other
- version of the tool you use: 1.2.1

### Issue Description

Hello,

When trying to install OHHTTPStubs on a project using Swift 4, I come across this error with the Swift versions being different. Will there be an update for supporting Swift 4? Here is a screenshot of the error:
![screen shot 2017-09-21 at 5 25 07 pm](https://user-images.githubusercontent.com/16155920/30719586-10f889f2-9ef2-11e7-8c1c-6cd2148ea217.png)

**Comment by Liquidsoul** [comment]
Hi @eman6576,

From the error, it does not seem to be related to the `OHHTTPStubs` library but to its integration with cocoapods.
You are adding `OHHTTPStubs` as a dependency to targets with different Swift versions and it appears that cocoapods cannot handle this (or at least the version you use).
Could you try using the same swift version in your targets? Or If not possible, just remove temporarily `BaseAppV2IntegrationTests` to see if it works with only `Swift 4.0` integration?

Thanks!

**Comment by eman6576** [comment]
@Liquidsoul ,

I was able to compile by making all targets use Swift 4.0. I also forked OHHTTPStubs, migrated to Swift 4.0 and changed its targets to Swift 4.0.

**Comment by Liquidsoul** [comment]
I do not understand your need to have a fork here 🤔 
I tried to use the `6.0.0` version using cocoapods `1.3.1` on a project configured to use Swift 4.0 and everything seems to be working fine.
Could you check that on your end?
And in any case, if your problem is solved, please close the issue 🙇

**Comment by dimazen** [comment]
Hello, @Liquidsoul. Any chances to update OHHTTPStubs archive for the Carthage download (the one attached to the release)? It is compiled with Swift 2.2 which is quite old for today :)

**Comment by AliSoftware** [comment]
We decided to stop shipping precompiled binary releases due to the ABI stability not being there yet for Swift (otherwise we'd have to maintain one for each Swift version to make everyone happy and I don't have that maintenance bandwidth)

**Comment by AliSoftware** [comment]
Closing this as it's not an issue which requires any action by OHHTTPStubs itself, but by Carthage relying on the Swift ABI being stable while it's not. 

This issue is thus common to _any_ Swift library that you integrate with Carthage and provides a compiled binary, not just OHHTTPStubs. 
To solve it just use the `--no-use-binaries` flag when invoking Carthage, or open an issue in the Carthage repo to all them to auto-fallback to that flag in case of binary ABI incompatibility detected (I thought they already implemented that fallback though so be sure to use the latest version of Carthage too)
