### ISSUE TITLE
Typo in Wiki

### ISSUE THREAD

**Issue by michaello** [AliSoftware/OHHTTPStubs#261]
Hey there,

I noticed a [small typo](https://github.com/AliSoftware/OHHTTPStubs/wiki/Usage-Examples) in ```headers```:

```
// Swift
stub(isHost("mywebservice.com")) { request in
  // Stub it with our "wsresponse.json" stub file
  return OHHTTPStubsResponse(
    fileAtPath: OHPathForFile("wsresponse.json", type(of: self))!,
    statusCode: 200,
    headers: ["Content-Type":@"application/json"]
  )
}
```

I guess someone is fond of good ol' Obj-C with this ```@``` 🐨

Cheers!

**Comment by AliSoftware** [comment]
Nicely spotted, thanks! 

Just fixed it 👌
