### ISSUE TITLE
Redirect 307 and 308 are changing from POST to GET and that's not allowed

### ISSUE THREAD

**Issue by mikelupo** [AliSoftware/OHHTTPStubs#262]
Oliver, I can see in the code that OHHTTStubs is not preserving the method type (i.e. POST vs GET) in 
https://github.com/AliSoftware/OHHTTPStubs/blob/master/OHHTTPStubs/Sources/OHHTTPStubs.m:427 
OHHTTPStubs.m creates an immutable request object without respect to whether the original request method was a POST or a GET. This goes against HTTP1.1 for the 307 and against RFC 7538 for the 308. In the case of 307 or 308 we need to preserve the request method in the redirect.

I'll post a pull request to fix this.

**Comment by AliSoftware** [comment]
Oh, nice catch! Thx!

I'll wait for your PR to do the release I was planning to do soon (it's been ages since I did a release and some fixes already in master are still waiting for release for a while). Let me know when you find time to do that PR so I can know if it's worth waiting for your for the release or not 😉

**Comment by mikelupo** [comment]
I've actually made the change, but I will need some help to add a test case for each of these redirects. I'll go ahead and post the PR so you can review the change just the same.

**Comment by AliSoftware** [comment]
:+1:
I think we have a "WIP" GitHub label don't hesitate to use it on the PR if there are some tasks still to do / tests still to add before merging

**Comment by mikelupo** [comment]
It seems like it would be rudimentary to add a label to a PR or Bug. I can see the categories on the right hand side of the web page, but it's immutable. I can't add any label. @AliSoftware can you please intervene?

**Comment by AliSoftware** [comment]
@mikelupo I've invited you as a collaborator so as soon as you accept the invitation you should have the rights to add labels now 👍  (tbh I was surprised that I didn't invite you as an official collaborator on the repo before 😉 )

**Comment by mikelupo** [comment]
@AliSoftware  It's mutable now. I can add a label, but we don't currently have a WIP label. Shall I create one?

**Comment by AliSoftware** [comment]
Oh yeah sure I think it will always be useful to have 👍
