### ISSUE TITLE
Any plans to support swift 4.x?

### ISSUE THREAD

**Issue by Nonnus** [AliSoftware/OHHTTPStubs#278]
### New Issue Checklist

- [x] I have tried with the latest version of OHHTTPStubs
- [x] I have read the [README](https://github.com/AliSoftware/OHHTTPStubs/blob/master/README.md)
- [x] I have read the [Using the right Swift Version of `OHHTTPStubs` for your project](https://github.com/AliSoftware/OHHTTPStubs#using-the-right-swift-version-of-ohhttpstubs-for-your-project) section
- [x] I have searched in the [existing issues](https://github.com/AliSoftware/OHHTTPStubs/issues?utf8=✓&q=is%3Aissue)
- [x] I have read [the OHHTTPStubs wiki](https://github.com/AliSoftware/OHHTTPStubs/wiki) to see if there wasn't a detailed page talking about my issue

### Environment

- version of OHHTTPStubs: [LIB VERSION HERE]
- integration method you are using:
  * [ ] Cocoapods
  * [x] Carthage
  * [ ] submodule
  * [ ] other
- version of the tool you use: [INSERT VERSION HERE]

### Issue Description
Whenever i try to rebuild OHHTTPStubs with XCode 9.x / Swift 4.x using carthage i get a warning stating framework was build with swift 3.1 

##### Complete output when you encounter the issue (if any)

```
*** Skipped installing OHHTTPStubs.framework binary due to the error:
	"Incompatible Swift version - framework was built with 3.1 (swiftlang-802.0.53 clang-802.0.42) and the local version is 4.1 (swiftlang-902.0.48 clang-902.0.37.1)."
```

**Comment by AliSoftware** [comment]
See #277
