### ISSUE TITLE
Unreliable redirect test

### ISSUE THREAD

**Issue by Liquidsoul** [AliSoftware/OHHTTPStubs#280]
### New Issue Checklist

- [x] I have tried with the latest version of OHHTTPStubs
- [x] I have read the [README](https://github.com/AliSoftware/OHHTTPStubs/blob/master/README.md)
- [x] I have read the [Using the right Swift Version of `OHHTTPStubs` for your project](https://github.com/AliSoftware/OHHTTPStubs#using-the-right-swift-version-of-ohhttpstubs-for-your-project) section
- [x] I have searched in the [existing issues](https://github.com/AliSoftware/OHHTTPStubs/issues?utf8=✓&q=is%3Aissue)
- [x] I have read [the OHHTTPStubs wiki](https://github.com/AliSoftware/OHHTTPStubs/wiki) to see if there wasn't a detailed page talking about my issue

### Environment

- version of OHHTTPStubs: `master`

### Issue Description

Following the introduction of #263 the test `- [NSURLSessionTests test_NSURLSessionDefaultConfig_MethodAndDataRetentionOnRedirect]` fails _most of the time_ (see @AliSoftware [comment](https://github.com/AliSoftware/OHHTTPStubs/pull/263#issuecomment-344105021)).
We need to investigate this issue so that we can have a reliable CI.

**Comment by Liquidsoul** [comment]
Ok, after some investigations this seems related to https://github.com/AliSoftware/OHHTTPStubs/issues/230#issuecomment-378385218

I have experienced the same issues (redirect data without response object) for the failures.
So this seems like a `NSURLProtocol` bug.

So now I see several options:
- we find a workaround in the library to make this reliable (that seems unlikely to me)
- we find a workaround for the tests, but this would mean that client code can fail, and this occurs a lot in the tests in my experience
- we disable the tests and document that redirections are not correctly supported by `OHHTTPStubs` because of an Apple bug

**Comment by AliSoftware** [comment]
😢

I think we'll have to go with solution 3 then. I think we could still keep the code handling the redirections, but just document properly that there are issues due to the Apple bug.
