### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by jonasman** [AliSoftware/OHHTTPStubs#311]
### New Issue Checklist

- [x] I have tried with the latest version of OHHTTPStubs
- [x] I have read the [README](https://github.com/AliSoftware/OHHTTPStubs/blob/master/README.md)
- [x] I have read the [Using the right Swift Version of `OHHTTPStubs` for your project](https://github.com/AliSoftware/OHHTTPStubs#using-the-right-swift-version-of-ohhttpstubs-for-your-project) section
- [x] I have searched in the [existing issues](https://github.com/AliSoftware/OHHTTPStubs/issues?utf8=✓&q=is%3Aissue)
- [x] I have read [the OHHTTPStubs wiki](https://github.com/AliSoftware/OHHTTPStubs/wiki) to see if there wasn't a detailed page talking about my issue

### Environment

- version of OHHTTPStubs: Any
- integration method you are using:
  * [ ] Cocoapods
  * [ ] Carthage
  * [ ] submodule
  * [x] other
- version of the tool you use: Xcode 11

### Issue Description

Any plans to Integrate Swift Package Manager? 
It is now a first class citizen on Xcode 11

##### Complete output when you encounter the issue (if any)

**Comment by jeffctown** [comment]
I love this idea, we should support SPM.  I haven't converted anything with so many subspecs before, so hopefully the current subspecs could be easily converted to several packages.  @AliSoftware do you have any thoughts or preferences here?

**Comment by sunshinejr** [comment]
Ah yeah the SPM support, I mentioned it to @AliSoftware but I never had time to do that. But I will happily help with reviewing the PR.

**Comment by jonasman** [comment]
@jeffctown from my quick read the submodules are for Objc. The swift one is just a module. 
so for SPM we could make one and include all the code. Later on improve and start dividing the modules or am i not seeing this right?

**Comment by jonasman** [comment]
@jeffctown Maybe adding all the files for now and later evaluate how to make the sub packages. 
In fact sub dependencies are supported by SPM but i think it needs to be one per repo.

**Comment by gabrielPeart** [comment]
Yes, sub dependencies are supported, I believe that is very important to add support for SPM. Any news about it? @jeffctown  @AliSoftware ?

**Comment by jeffctown** [comment]
I'm working on this.  I hope to be able to get it in soon.
