### ISSUE TITLE
Xcode 12 - Warnings related to iOS 8 support (Swift Package Manager)

### ISSUE THREAD

**Issue by spekke** [AliSoftware/OHHTTPStubs#328]
### New Issue Checklist

- [x] I have tried with the latest version of OHHTTPStubs
- [x] I have read the [README](https://github.com/AliSoftware/OHHTTPStubs/blob/master/README.md)
- [x] I have read the [Using the right Swift Version of `OHHTTPStubs` for your project](https://github.com/AliSoftware/OHHTTPStubs#using-the-right-swift-version-of-ohhttpstubs-for-your-project) section
- [x] I have searched in the [existing issues](https://github.com/AliSoftware/OHHTTPStubs/issues?utf8=✓&q=is%3Aissue)
- [x] I have read [the OHHTTPStubs wiki](https://github.com/AliSoftware/OHHTTPStubs/wiki) to see if there wasn't a detailed page talking about my issue

### Environment

- version of OHHTTPStubs: 9.0.0
- integration method you are using:
  * [ ] Cocoapods
  * [ ] Carthage
  * [ ] submodule
  * [x] other (Swift Package Manager)
- version of the tool you use: Xcode 12

### Issue Description

When building a project that integrates OHTTPStubs via Swift Package Manager - Xcode 12 outputs the following warning message. 

##### Complete output when you encounter the issue (if any)

```
The iOS Simulator deployment target ‘IPHONEOS_DEPLOYMENT_TARGET’ is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target ‘OHHTTPStubsSwift’ from project ‘OHHTTPStubs’)
```

**Comment by ThomWee** [comment]
Would be nice if the project settings can be updated soon. Or is this project no longer maintained? Last change was beginning of this year.

**Comment by jeffctown** [comment]
@ThomWee There definitely isn't much activity here these days.   

@kikeenrique If you would be nice enough to submit a PR for that, I'd be happy to accept it.

**Comment by kikeenrique** [comment]
@jeffctown Thanks for your offering. I've already created a PR.

**Comment by Kaspik** [comment]
@jeffctown Hey! Is there a plan to release this as a `tag`/`release` for SPM users so we don't have to point to commit / branch? Thanks.

**Comment by jeffctown** [comment]
Sure, I can do that @Kaspik .  I put up a [PR](#337) to handle it.
