### ISSUE TITLE
Mocktail support

### ISSUE THREAD

**Issue by santiagotimothy** [AliSoftware/OHHTTPStubs#331]
### New Issue Checklist

- [x] I have tried with the latest version of OHHTTPStubs
- [x] I have read the [README](https://github.com/AliSoftware/OHHTTPStubs/blob/master/README.md)
- [x] I have read the [Using the right Swift Version of `OHHTTPStubs` for your project](https://github.com/AliSoftware/OHHTTPStubs#using-the-right-swift-version-of-ohhttpstubs-for-your-project) section
- [x] I have searched in the [existing issues](https://github.com/AliSoftware/OHHTTPStubs/issues?utf8=✓&q=is%3Aissue)
- [x] I have read [the OHHTTPStubs wiki](https://github.com/AliSoftware/OHHTTPStubs/wiki) to see if there wasn't a detailed page talking about my issue

### Environment

- version of OHHTTPStubs: 8.0.0 to 9.0.0
- integration method you are using:
  * [ ] Cocoapods
  * [x] Carthage
  * [ ] submodule
  * [x] other (SPM)
- version of the tool you use: 0.36.0

### Issue Description

Our project is moving to Swift Package Manager from Carthage (OHHTTPStubs 8.0.0) and found out that Mocktails are not supported by the package generated by the project, any chance this gets supported soon?

Previous implementation:

`OHHTTPStubs.stubRequests(usingMocktailNamed: file, in: self.bundle, error: &error)`

**Comment by CognitiveWin** [comment]
I'd like to use Mocktails, too. Via SPM.

**Comment by natebird** [comment]
It looks like @fabrizioCorut has an open PR for this - https://github.com/AliSoftware/OHHTTPStubs/pull/340.
