### ISSUE TITLE
Module 'OHHTTPStubs' has no member named 'removeAllStubs' in 9.0.0

### ISSUE THREAD

**Issue by hungwei0331** [AliSoftware/OHHTTPStubs#336]
I had updated the OHHTTPStubs to 9.0.0,

Following the official document as below,

"remove any stubs you installed after each test — to avoid those stubs to still be installed when executing the next Test Case — by calling [HTTPStubs removeAllStubs] in your tearDown method."

but when i calling OHHTTPStubs.removeAllStubs() 

it appear Module 'OHHTTPStubs' has no member named 'removeAllStubs',

which function should I write or instead,

thanks for any comment in advance

**Comment by hungwei0331** [comment]
i found it rename to HTTPStubs

so call HTTPStubs.removeAllStubs() would be solved it.

**Comment by ppamorim** [comment]
@AliSoftware Could you please rename it in the documentation?
