### ISSUE TITLE
Stub not being called

### ISSUE THREAD

**Issue by brennon** [AliSoftware/OHHTTPStubs#47]
I'm setting up a stub in an Specta spec that isn't getting called. Here's the code I'm using:

```
it(@"should request splashes", ^{
    __block BOOL success = NO ;

    [OHHTTPStubs stubRequestsPassingTest:^BOOL(NSURLRequest *request) {
        return [request.URL.host isEqualToString:@"zamba.cs.vt.edu"];
    }
                        withStubResponse: ^OHHTTPStubsResponse *(NSURLRequest *request) {
                            NSData *stubData = [NSData dataWithContentsOfFile:[[NSBundle mainBundle] pathForResource:@"findSplashesResponse" ofType:@"txt"]];
                            NSDictionary *standardHeaders = @{ @"Content-Type":@"text/html"};
                            return [OHHTTPStubsResponse responseWithData:stubData statusCode:200 headers:standardHeaders];
                        }].name = @"findSplashes.php";
    [OHHTTPStubs setEnabled:YES];

    [client POST:@"findSplashes.php"
      parameters:@{ @"hash": [client hashString],
                    @"lat":[NSString stringWithFormat:@"%f", vt.coordinate.latitude],
                    @"long":[NSString stringWithFormat:@"%f", vt.coordinate.longitude],
                    @"radius":@"1600" }
         success:^(NSURLSessionDataTask *task, id responseObject) {
             NSString *response = [[NSString alloc] initWithData:(NSData *) responseObject encoding:NSUTF8StringEncoding];
             success = [response isEqualToString:@"252\t5527.5387976613\t4\t4\t1387655919\t1387568319\t300\t40.739983\t-73.992951\n"] ? YES : NO;
         }
         failure:^(NSURLSessionDataTask *task, NSError *error) {
             success = NO;
         }];

    expect(success).will.beTruthy();
});
```

`client` is a singleton instance of an `AFHTTPSessionManager` from AFNetworking 2.0. Strangely, this test and other similar tests were passing originally--I don't know what I've done to break them! When the POST request is made, I can check that `OHHTTPStubs.sharedInstance` is the same as when the stub was created. I've added the `+[OHHTTPStubs setEnabled:] call per other issues here. The block passed as the`stubRequestsPassingTest:` parameter is never executed--all requests hit the network. Any ideas? Thanks!

**Comment by nicolasmiari-unext** [comment]
I already have the host application set to "None" (I'm testing a Framework). 
The test block is called for requests other than my own (e.g. host: static.realm.io), but not for mine. Instead, I get `NSURLErrorCancelled`...

**Comment by AliSoftware** [comment]
Background sessions are handled by the system itself, we can't hook on them as they are performed out-of-process and thus or of reach for interception. See the "limitations" section in the README.

**Comment by nicolasmiari-unext** [comment]
@AliSoftware Thank you, I missed that.
I'll be using the default session for my unit tests (Can't unit-test background downloads anyway).
