### ISSUE TITLE
Body of request never makes it to stubRequestPassingTest:

### ISSUE THREAD

**Issue by jpalten** [AliSoftware/OHHTTPStubs#52]
I use OHHTTPStubs to test if my AFHTTPRequest send the correct xml as body in a request. This works fine and all tests pass, checking the body that would be sent in the stubRequestPassingTest:

Now I moved to using AFHTTPSessionManager, and the program still works fine, but the tests fail, telling me that the body to be sent is empty, instead of the expected xml.

Something funny that happens: the request that gets prepared by my program has a different pointer (0xe1efbc0) than the request (0xe2c3310) that is checked in the stub. Any idea what is going on? Is it possible the requests gets copied, but the body didn't make it to the copy?

Here is a log from my console:

2014-02-06 14:09:36.278 xctest[69495:303] Posting request 0xe1efbc0 with body: <ajax-request action="getstat" comp="system"></ajax-request>
2014-02-06 14:09:36.278 xctest[69495:1903] Stubbing url /admin/_cmdstat.jsp
2014-02-06 14:09:36.278 xctest[69495:1903] checking body of request 0xe2c3310
2014-02-06 14:09:36.279 xctest[69495:1903] Would sent body: 
/Volumes/InternalHD/Projecten/ZoneDirectorViewer/ZoneDirectorViewer/Connection/ServerConnectionTests.m:551: error: -[ServerConnectionTests testGetSystemInfo] : ((requestedBody) equal to (expectedBody)) failed: ("") is not equal to ("<ajax-request action="getstat" comp="system"></ajax-request>")

**Comment by samskiter** [comment]
Hi, not using OHHTTPStubs, but stumbled into this while hitting exactly this issue myself. Found your discussion very useful for diagnosing the problem. Boiled it down and produced a project demonstrating the problem at it's simplest (and the difference between NSURLSession and NSURLConnection) - https://github.com/samskiter/testnsurlprotocol

Thanks for the information everyone and thanks @AliSoftware for the workaround

**Comment by AliSoftware** [comment]
@samskiter thx for the feedback :+1:

**Comment by AliSoftware** [comment]
Hi all, this issue should now have a workaround thanks to #166 (which has just been merged into master)!
You'll now be able to use the new `OHHTTPStubs_HTTPBody` property on `NSURLRequest` if you want to test your request body in stubs even after iOS cleared the native property now.

Will update the wiki entry and do a release soon.
