### ISSUE TITLE
Ability to programmatically trigger the finish of the request

### ISSUE THREAD

**Issue by lukabernardi** [AliSoftware/OHHTTPStubs#53]
Right now the only thing that is possible to do to control when a response is returned is to specify the `responseTime:`. 
This is not ideal especially if your writing you test because you need to rely of timing instead of actual method call.

**Comment by AliSoftware** [comment]
Closing this as it has been open for too long without any new propositions. Feel free to reopen if any idea to propose this comes to mind but I think this is conceptually impossible.
