### ISSUE TITLE
Correct way to stub HTTP requests when doing Application Tests with KIF

### ISSUE THREAD

**Issue by jmburges** [AliSoftware/OHHTTPStubs#58]
Hey!

OHHTTPStubs is obviously super awesome and I use it for my unit tests, but now I'm starting to do application tests with KIF and would like to stub out those connections. What are the best practices for doing that? I know I could put the code in my `didFinishLaunchingWithOptions:` method, but then it also happens when you are running the application locally. Currently I've hacked it and put it in the `KIFTestActor` `load` method, and I was thinking of creating an `OHHTTPStubs` `load method to put it in. Any ideas?

**Comment by jmburges** [comment]
Hey @AliSoftware you would think the `- (void)beforeAll` would do it but it doesn't! it looks like the beforeAll block gets run earlier enough if you hit the internet on `viewDidLoad`.

**Comment by AliSoftware** [comment]
Hi @jmburges 

Since I don't know KIF I probably won't be of any help here. I suggest you ask your question on StackOverflow to see if KIF users have some insight on where to put that initialisation code in KIF.
