### ISSUE TITLE
OHHTTPStubs not working with iOS8 & Swift

### ISSUE THREAD

**Issue by cvasilak** [AliSoftware/OHHTTPStubs#65]
Hi all,

I am trying to use OHHTTPStubs under Swift on iOS 8. Not sure what I am doing wrong but so far was unable to make it work. Here is exempt of the code that setup's the stub

```
 OHHTTPStubs.stubRequestsPassingTest({ (request: NSURLRequest!) -> Bool in
     return true
}, withStubResponse:( { (request: NSURLRequest!) -> OHHTTPStubsResponse in
    return OHHTTPStubsResponse(data:NSData.data(), 
                                             statusCode: 200, headers: ["Content-Type" : "text/json"])
}))

// initialize NSURLSession and make request
```

Unfortunately the stub is not called making the test fail with a 404. Am i doing sth wrong or the lib not yet supported on iOS 8 (presumably sth has changed there) ?

Regards

**Comment by AliSoftware** [comment]
Hi @cvasilak I just saw @corinnekrych at dotSwift that told me you are using your own implementation of `OHHTTPStubs`, I'd be very interesting in getting in touch to see how we can team up for Swift support in `OHHTTPStubs`!

**Comment by cvasilak** [comment]
Hi @AliSoftware thank you for getting in touch! 
Mainly our [aerogear-ios-httpstub](https://github.com/aerogear/aerogear-ios-httpstub) project was started at the same time as our Swift [httplib](https://github.com/aerogear/aerogear-ios-http) work where we needed a stub framework(preferably in Swift). Back then though, there wasn't any and because we were familiar with the awesome OHTTPStubs and experimenting/learning Swift, we thought to create one inspired by it.

From my view and @corinnekrych, I think maybe continue development of our Swift httpstub framework, as we do now, and possible include a link in your repository Readme.md of sth 'If you are working with Swift, you may be interested at this Swift port of HTTPStub' or something you think more appropriate. Currently not all features of OHTTPStubs are supported but it will be just awesome to have your experience and contributions.

What do you think?

Thanks again for getting in touch!

**Comment by AliSoftware** [comment]
Let's move that discussion in [a dedicated issue](https://github.com/aerogear/aerogear-ios-httpstub/issues/15) to avoid spamming this one ;)
