### ISSUE TITLE
OHHTTPSTubs interfering with Task countOfBytesSent

### ISSUE THREAD

**Issue by jcampbell05** [AliSoftware/OHHTTPStubs#76]
When I have a stubbed method the countOfBytesSent seems to strip the content length and even prevent countOfBytesSent from being updated for a nsurlsessiontask.

Removing the stubs however causes it to work perfectly.

**Comment by AliSoftware** [comment]
up

**Comment by jcampbell05** [comment]
Sorry, sort of let this one slip, I'll get a example prepared
