### ISSUE TITLE
Interfering with push notification registration

### ISSUE THREAD

**Issue by asymptotik** [AliSoftware/OHHTTPStubs#77]
I found this library very useful, however, I want to point out that when this library is simply included in a project the +(void)load method in NSURLSessionConfiguration(OHHTTPStubsSupport) is called. This interferes with things like Amazons SDK and registering for push notifications even when none of the header are included or any of the methods used. The docs mention to use this code as part of a test target or use it in `#if DEBUG`. Using it in `#if DEBUG` statements is not enough. The swizzling still occurs and can create very hard to track down issues with other networking code. In my case Amazon SDK networking calls and registering for push notifications were simply not working after any of my own networking calls. My solution was to completely remove the source from my project. It's a really nice tool to have. Perhaps a way to have it play nicely when not in use and without having to remove it from my code or maintain another target would be very helpful. I'm sorry I don't have a code sample. Perhaps I can get something soon. It's not straight forward as I was only having issues after some of my own networking calls were made. Anywho, I just wanted to get this on your radar for now.

**Comment by AliSoftware** [comment]
Closing for lack of input. Please reopen if you got any news or sample code to reproduce.
