### ISSUE TITLE
Problems with iOS 7.1 and Swift

### ISSUE THREAD

**Issue by aleufms** [AliSoftware/OHHTTPStubs#93]
Xcode 6.2
OHHTTPStubs 3.1.11
CocoaPods 0.36.1

Tried to run tests on iOS 7.1 simulator in a Swift project and it doesn't work:
Obs. 1: on iOS 8.1 simulator works fine
Obs. 2: run pod without use_frameworks! config, because I want to support iOS 7

IDEBundleInjection.c: Error 3588 loading bundle '/Users/me/Library/Developer/Xcode/DerivedData/myapp-cypnccujdzumvjcxeuymxljgxetv/Build/Products/Debug-iphonesimulator/UITests.xctest': The bundle “UITests” couldn’t be loaded.
DevToolsBundleInjection environment:
XCInjectDiagnostics: (null)
XCInjectBundleInto: /Users/me/Library/Developer/Xcode/DerivedData/myapp-cypnccujdzumvjcxeuymxljgxetv/Build/Products/Debug-iphonesimulator/myapp.app/myapp
XCInjectBundle: /Users/me/Library/Developer/Xcode/DerivedData/myapp-cypnccujdzumvjcxeuymxljgxetv/Build/Products/Debug-iphonesimulator/UITests.xctest
TestBundleLocation: /Users/me/Library/Developer/Xcode/DerivedData/myapp-cypnccujdzumvjcxeuymxljgxetv/Build/Products/Debug-iphonesimulator/UITests.xctest
TMPDIR: /Users/me/Library/Developer/CoreSimulator/Devices/7B46887A-C6CF-468B-8AD5-C526D8D095D4/data/Applications/799AB217-E68E-44C7-8422-60BEE1F2A0E6/tmp
DYLD_LIBRARY_PATH: /Users/me/Library/Developer/Xcode/DerivedData/myapp-cypnccujdzumvjcxeuymxljgxetv/Build/Products/Debug-iphonesimulator
DYLD_INSERT_LIBRARIES: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/IDEBundleInjection.framework/IDEBundleInjection
DYLD_FRAMEWORK_PATH: /Users/me/Library/Developer/Xcode/DerivedData/myapp-cypnccujdzumvjcxeuymxljgxetv/Build/Products/Debug-iphonesimulator
DYLD_FALLBACK_LIBRARY_PATH: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 7.1.simruntime/Contents/Resources/RuntimeRoot/usr/lib
DYLD_FALLBACK_FRAMEWORK_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks

**Comment by AliSoftware** [comment]
Hi @aleufms 

I don't think that's an issue related to `OHHTTPStubs` on itself.

See those related questions on StackOverflow: [here](http://stackoverflow.com/questions/25488425/cannot-run-tests-on-xcode-6-beta-5) and [here](http://stackoverflow.com/questions/25079775/test-bundle-could-not-be-loaded-because-an-unanticipated-error) (and probably others).

Feel free to try those and give me feedback if it works for you or not.

**Comment by aleufms** [comment]
Hi,

I tried the solutions on StackOverflow without success. I think it is a bug on XCode. I have to force use framework on my test target for it works.

**Comment by AliSoftware** [comment]
Ok. Could you attach a sample test project here to help us reproduce the issue, to ensure it's unrelated to `OHHTTPStubs` itself? Thx

**Comment by AliSoftware** [comment]
Closed due to lack of reproducibility and because it is most likely a bug in Xcode itself.
