### ISSUE TITLE
Carthage support not working

### ISSUE THREAD

**Issue by MichaelMcGuire** [AliSoftware/OHHTTPStubs#97]
When adding OHHTTPStubs per the instructions in the README, the framework is not building.  Someone reported it on the Carthage project (Carthage/Carthage#405).  It looks like the Example project is found before the main project.  Not sure if you want to change the structure for Carthage support, but the README should probably at least be updated for now.

**Comment by AliSoftware** [comment]
Thanks for reporting!

I am beginning to think that I'll drop Carthage support. Too much work as a lib maintainer, that's the 4th issue I had to fix just to workaround Carthage bugs so far in a short amount of time; each time I fix a thing for Carthage another issue arise… I don't have time for this.

I'll fix the README accordingly. Thanks!

**Comment by YasKuraishi** [comment]
@AliSoftware - the fix was pretty trivial fix, just had to rename Example folder to Sample so Carthage could find the project file. PR waiting for your seal of approval... https://github.com/AliSoftware/OHHTTPStubs/pull/98

**Comment by AliSoftware** [comment]
Now that I moved Example projects down a level (as I added a Swift demo project alongside the already existing ObjC demo project), Carthage should not use the Example project(s) anymore.

This modification has been done on `master` so feel free to test it. I'll release `4.0.0` later in the week-end once I finished removing some legacy code.

**Comment by AliSoftware** [comment]
Closing due to lack of feedback. Should theoretically be fixed anyway (I don't use Carthage so won't test myself)

**Comment by MichaelMcGuire** [comment]
Sorry for the lack of feedback!  I just converted over to using Carthage from CocoaPods on the latest in master (4.0.1) and everything is working great.  Thanks!

**Comment by AliSoftware** [comment]
Thanks for letting me know :)
